"""Codegen: compile a ``.epeg`` grammar and emit C++ that rebuilds the identical
GPDA graph + lexer table for the tokenized C++ engine (``gpda_tok``).

The ``.epeg`` file stays the single source of truth: this tool loads it through
loom's Python compiler (the same one loom uses), then serialises the *compiled*
graph (nodes, links, rules, skip-types, start-rule) and the auto-lexer's rule
table into a self-contained C++ translation unit.  Re-run it whenever the
grammar changes; the generated file is checked in alongside the vendored engine
so ftrace builds without a Python step.

This is the bridge for the J3c validation shim: ftrace runs the shared grammar
(via this generated graph + the reusable ``gpda_lexer.hpp``) alongside its
hand-written parser and diffs the two Block trees.

Scope: the emitter supports exactly the node kinds the shared scene grammar
compiles to — MATCH_STR / MATCH_TOK / RULE_REF / SPLIT / RULE_START / RULE_END.
It errors (rather than silently mis-emitting) on predicates, subtraction,
left-recursion, captures, or actions, none of which the scene grammar uses.
If a future grammar needs them, extend the emitter *and* the C++ engine paths
together — don't work around it here.

Usage:
    python -m loom.grammar.emit_cpp GRAMMAR.epeg FUNC_BASENAME > out.gen.cpp
    python -m loom.grammar.emit_cpp ftsl_scene.epeg ftsl_scene       # default paths
"""
from __future__ import annotations

import os
import sys

from ._gpda import load_grammar, NT

HERE = os.path.dirname(os.path.abspath(__file__))

_NT_TO_CPP = {
    NT.MATCH_STR: "MatchStr",
    NT.MATCH_TOK: "MatchTok",
    NT.RULE_REF: "RuleRef",
    NT.SPLIT: "Split",
    NT.RULE_START: "RuleStart",
    NT.RULE_END: "RuleEnd",
}
_UNSUPPORTED = {
    NT.PRED_NOT: "negative lookahead !(...)",
    NT.PRED_AND: "positive lookahead &(...)",
    NT.SUB_CHECK_NOT: "EBNF subtraction A - B",
    NT.ACTION: "semantic action {{ ... }}",
}


def _cpp_str(s: str) -> str:
    """A C++ string literal for an arbitrary Python string (raw regex etc.)."""
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.append(f"\\x{ord(ch):02x}")
    out.append('"')
    return "".join(out)


def _collect_nodes(parser):
    """All graph nodes reachable from every rule, in a stable order.

    Order = ascending Python Node.id, which the builder assigns deterministically
    for a given grammar; we remap to dense 0..N-1 indices for the C++ side.
    """
    seen = {}

    def walk(n):
        if n.id in seen:
            return
        seen[n.id] = n
        for m in n.links:
            walk(m)

    for _name, (start, end) in parser.rules.items():
        walk(start)
        walk(end)
    ordered = [seen[i] for i in sorted(seen)]
    idx = {n.id: k for k, n in enumerate(ordered)}
    return ordered, idx


def emit(grammar_text: str, func_base: str) -> str:
    gp = load_grammar(grammar_text)
    parser = gp.parser
    lexer = gp.lexer

    if parser.lr_meta:
        raise ValueError(f"grammar uses left-recursion (lr_meta={parser.lr_meta}); "
                         "not supported by the C++ emitter")
    if parser.stripped_names:
        raise ValueError(f"grammar uses subtraction / stripped rules "
                         f"({parser.stripped_names}); not supported by the C++ emitter")
    if parser.capture_names:
        raise ValueError(f"grammar uses captures ({parser.capture_names}); "
                         "not supported by the C++ emitter")

    ordered, idx = _collect_nodes(parser)
    for n in ordered:
        if n.type in _UNSUPPORTED:
            raise ValueError(f"grammar uses {_UNSUPPORTED[n.type]} (node {n.id}); "
                             "not supported by the C++ emitter")
        if n.type not in _NT_TO_CPP:
            raise ValueError(f"unknown node type {n.type} (node {n.id})")

    L = []
    ap = L.append
    ap(f"// GENERATED by loom.grammar.emit_cpp from a .epeg grammar -- DO NOT EDIT.")
    ap(f"// Regenerate:  python -m loom.grammar.emit_cpp <grammar>.epeg {func_base}")
    ap(f"//")
    ap(f"// Rebuilds the compiled GPDA graph + auto-lexer table for the tokenized")
    ap(f"// C++ engine (gpda_tok), so the .epeg stays the single source of truth.")
    ap('#include "tokenized.hpp"')
    ap('#include "gpda_lexer.hpp"')
    ap("")
    ap("namespace ftsl_gen {")
    ap("")
    ap(f"gpda_tok::Graph build_{func_base}_graph() {{")
    ap("    using gpda_tok::Graph;")
    ap("    using gpda_tok::NodeType;")
    ap("    Graph g;")
    ap(f"    g.nodes.resize({len(ordered)});")
    ap("")
    for n in ordered:
        i = idx[n.id]
        cpp_ty = _NT_TO_CPP[n.type]
        ap(f"    g.nodes[{i}].type = NodeType::{cpp_ty};")
        if n.type in (NT.MATCH_STR, NT.MATCH_TOK, NT.RULE_REF) and n.value is not None:
            ap(f"    g.nodes[{i}].value = {_cpp_str(n.value)};")
        if n.type in (NT.RULE_START, NT.RULE_END) and n.rule is not None:
            ap(f"    g.nodes[{i}].rule_name = {_cpp_str(n.rule)};")
        if n.links:
            links = ", ".join(str(idx[m.id]) for m in n.links)
            ap(f"    g.nodes[{i}].links = {{{links}}};")
        ap("")
    # rules
    for name, (start, end) in sorted(parser.rules.items()):
        ap(f"    g.rules[{_cpp_str(name)}] = {{{idx[start.id]}u, {idx[end.id]}u}};")
    ap("")
    skips = ", ".join(_cpp_str(s) for s in sorted(parser.skip_types))
    ap(f"    g.skip_types = {{{skips}}};")
    ap(f"    g.start_rule = {_cpp_str(parser.start_rule)};")
    ap("    g.finalize();")
    ap("    return g;")
    ap("}")
    ap("")
    # lexer table
    ap(f"std::vector<gpda_lex::LexRule> {func_base}_lex_rules() {{")
    ap("    return {")
    for name, pat in lexer.rules:
        ap(f"        {{{_cpp_str(name)}, {_cpp_str(pat.pattern)}}},")
    ap("    };")
    ap("}")
    ap("")
    ap("}  // namespace ftsl_gen")
    ap("")
    return "\n".join(L)


def main(argv):
    grammar = argv[1] if len(argv) > 1 else os.path.join(HERE, "ftsl_scene.epeg")
    func_base = argv[2] if len(argv) > 2 else "ftsl_scene"
    with open(grammar, "r", encoding="utf-8") as fh:
        text = fh.read()
    sys.stdout.write(emit(text, func_base))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
