"""Generate the 2D detector's project config from `notes/keypoints.yaml`.

    python tools/keypoints_project.py --check
    python tools/keypoints_project.py --emit dlc   -o session/dlc/config.yaml
    python tools/keypoints_project.py --emit sleap -o session/sleap/skeleton.json
    python tools/keypoints_project.py --emit guide -o session/labelling_guide.md

**Why generate rather than write both.** DeepLabCut and SLEAP each keep their own list of
body parts and their own skeleton. If that list is typed out next to keypoints.yaml
instead of derived from it, the interface has two ends that each restate the
correspondence, and they disagree *silently*: the detector emits `l_elbow`, the fit looks
for `elbow_l`, that landmark contributes nothing to E_kp, and the only symptom is that
the foreleg fits slightly worse than the hind. Nothing raises, nothing logs. Generating
one end from the other makes that unrepresentable.

`--check` is the same idea pointed at an existing config: it re-derives the body-part
list and diffs it against a config already on disk, which is what you run after someone
has added a body part in the DLC GUI (an entirely reasonable thing to do, and the one
way drift can still be introduced).

The generated DLC config carries the labelling `guide` text as a comment beside each
body part. That is not decoration: the rig's sites are at JOINT CENTRES, not at the
palpable prominence a person instinctively clicks, and a constant offset between the two
is exactly what the anatomy fit absorbs by making a bone the wrong length.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from creaturelab.console import use_utf8  # noqa: E402

use_utf8()   # before argparse: --help is the thing a cp1252 console cannot print

from creaturelab.keypoints import (DEFAULT_PATH, KeypointError,   # noqa: E402
                                   KeypointSet, load_keypoints)


def emit_dlc(kps: KeypointSet, task: str, scorer: str) -> str:
    """A DeepLabCut `config.yaml`.

    Only the fields DLC actually reads are written, and the ones a human is expected to
    fill in are left obviously blank (`video_sets`) rather than guessed at -- a config
    that silently points at somebody else's videos is worse than one that errors.
    """
    width = max(len(k.label) for k in kps)
    parts = []
    for k in kps:
        pad = " " * (width - len(k.label))
        parts.append(f"- {k.label}{pad}   # {k.guide}")
    body = "\n".join(parts)
    skeleton = "\n".join(f"- - {a}\n  - {b}" for a, b in kps.skeleton)
    today = _dt.date.today()
    return f"""\
# GENERATED by tools/keypoints_project.py from {os.path.basename(kps.path)} --
# do not hand-edit the `bodyparts` or `skeleton` lists. Adding a body part here without
# adding it to keypoints.yaml gives you a landmark the fit will never read; renaming one
# gives you a landmark the fit will silently drop. Edit keypoints.yaml and regenerate.
#
# Everything else in this file IS yours to edit: video_sets, the training fractions, the
# net type, the frame-picking numbers. Re-running the generator preserves nothing, so
# take a copy first, or use --check to diff instead.
#
# The comment beside each body part is the labelling instruction. Read it before you
# click: these landmarks are JOINT CENTRES, not the bony bumps you can feel.

Task: {task}
scorer: {scorer}
date: {today:%b%d}
multianimalproject: false
identity: null

# Fill this in: one entry per view, e.g.
#   videos/cam0.mp4:
#     crop: 0, 1920, 0, 1080
video_sets: {{}}

bodyparts:
{textwrap.indent(body, '')}

skeleton:
{skeleton}
skeleton_color: black

start: 0
stop: 1
numframes2pick: 40
pcutoff: 0.6
dotsize: 6
alphavalue: 0.7
colormap: rainbow

TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
batch_size: 8

cropping: false
x1: 0
x2: 640
y1: 0
y2: 480

corner2move2:
- 50
- 50
move2corner: true
"""


def emit_sleap(kps: KeypointSet) -> str:
    """A SLEAP skeleton, in the plain form its Python API takes directly.

    SLEAP's own on-disk format is a networkx node-link dump with embedded type tags,
    which is not a thing to hand-generate. This is the input to the documented
    constructor instead, which is stable and readable:

        import json, sleap
        d = json.load(open("skeleton.json"))
        skel = sleap.Skeleton.from_names_and_edge_inds(d["nodes"], d["edges"])
    """
    idx = {k.label: i for i, k in enumerate(kps)}
    doc = {
        "_generated_by": "tools/keypoints_project.py",
        "_source": os.path.basename(kps.path),
        "_warning": ("do not hand-edit `nodes` -- it is the fit's view of the animal. "
                     "Edit notes/keypoints.yaml and regenerate."),
        "nodes": kps.labels,
        "edges": [[idx[a], idx[b]] for a, b in kps.skeleton],
        "symmetries": [[idx[k.label], idx[k.label.replace("_left", "_right")]]
                       for k in kps
                       if k.label.endswith("_left")
                       and k.label.replace("_left", "_right") in idx],
        "guide": {k.label: k.guide for k in kps},
    }
    return json.dumps(doc, indent=2) + "\n"


def emit_guide(kps: KeypointSet) -> str:
    """The labelling instructions, as something a person can read next to the GUI.

    Same text as the config comments, but ordered and formatted for a human who is about
    to click a few thousand points and needs the left/right warning in front of them.
    """
    lines = [f"# Labelling guide -- {kps.creature}", "",
             f"Generated from `{os.path.basename(kps.path)}`. "
             f"{len(kps)} landmarks per animal per frame.", "",
             "**Right and left are the ANIMAL's right and left, never yours.** This is "
             "the most common error in a multi-view session, it is invisible in any one "
             "view, and it produces a fit that looks converged with the legs swapped.",
             "",
             "**Click the joint CENTRE, not the bump you can feel.** Every site in the "
             "rig is the axis the joint turns about. The point of the hock, for "
             "instance, is a few centimetres behind the hock's axis. A constant offset "
             "does not average out -- the anatomy fit absorbs it by making the bone the "
             "wrong length.",
             "",
             "| # | landmark | where |", "|---|---|---|"]
    for i, k in enumerate(kps, 1):
        soft = " *(expect this one to be unreliable; label it anyway)*" if k.is_soft \
            else ""
        lines.append(f"| {i} | `{k.label}` | {k.guide}{soft} |")
    lines += ["", "If a landmark is out of frame or genuinely hidden, leave it "
                  "unlabelled. A guessed point is worse than a missing one: the fit "
                  "weights it exactly as hard as a real one."]
    return "\n".join(lines) + "\n"


def check_dlc(kps: KeypointSet, path: str) -> int:
    """Diff an existing DLC config's body-part list against the correspondence."""
    import yaml
    with open(path, "r", encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh) or {}
    have = list(cfg.get("bodyparts") or [])
    want = kps.labels
    if have == want:
        print(f"{path}: {len(have)} body parts, in the same order as "
              f"{os.path.basename(kps.path)}  ok")
        return 0
    extra = [b for b in have if b not in want]
    missing = [b for b in want if b not in have]
    print(f"{path}: DRIFTED from {os.path.basename(kps.path)}", file=sys.stderr)
    for b in extra:
        print(f"  in the detector but not the rig: {b!r} -- the fit will never read "
              f"this; every frame you label it is wasted", file=sys.stderr)
    for b in missing:
        print(f"  in the rig but not the detector: {b!r} -- this landmark will be "
              f"unobserved and nothing downstream will say so", file=sys.stderr)
    if not extra and not missing:
        print("  same set, different order -- harmless for DLC, but regenerate anyway "
              "so diffs stay readable", file=sys.stderr)
    return 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--keypoints", default=DEFAULT_PATH,
                    help="the correspondence file (default notes/keypoints.yaml)")
    ap.add_argument("--emit", choices=("dlc", "sleap", "guide"),
                    help="what to generate; omit with --check")
    ap.add_argument("-o", "--out", help="write here (default: stdout)")
    ap.add_argument("--check", metavar="CONFIG",
                    help="diff an existing DLC config's bodyparts against the rig")
    ap.add_argument("--task", default=None, help="DLC Task name (default: creature name)")
    ap.add_argument("--scorer", default="lab", help="DLC scorer name")
    args = ap.parse_args()

    try:
        kps = load_keypoints(args.keypoints)
    except (KeypointError, OSError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    if not kps.sigma_px_measured:
        # Worth saying at the moment a labelling project is created, because measuring it
        # needs exactly the thing that is about to be produced: doubly-labelled frames.
        print(f"note: {os.path.basename(kps.path)} still carries the placeholder "
              f"detector noise ({kps.sigma_px_default} px). Double-label ~20 frames from "
              f"this session and replace it.", file=sys.stderr)

    if args.check:
        return check_dlc(kps, args.check)
    if not args.emit:
        print(f"{kps.path}: {len(kps)} landmarks, {len(kps.skeleton)} skeleton edges, "
              f"rig {kps.rig}")
        print("nothing to do: pass --emit dlc|sleap|guide, or --check CONFIG")
        return 0

    if args.emit == "dlc":
        text = emit_dlc(kps, args.task or kps.creature, args.scorer)
    elif args.emit == "sleap":
        text = emit_sleap(kps)
    else:
        text = emit_guide(kps)

    if args.out:
        os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".", exist_ok=True)
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"{len(kps)} landmarks -> {args.out}")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
