"""Which piece in gallery_rain actually throws a COLOURED caustic, and from how high?

The user's question was "the sphere's caustic has no colour -- will the glass gyroid give
me colour?".  This is the rig that answers it with numbers instead of theory: one stripped
top-down scene, one piece at a time, floated over a plain white cap in the gallery's own
sun, seen flat from above.

WHY THE OBVIOUS METRIC DOES NOT WORK.  Mode D renders one HERO WAVELENGTH per sample, so a
dispersive caustic arrives as chromatic SPECKLE: every pixel is some random monochromatic
spike and per-pixel saturation measures the sampler, not the optics.  The fix is the same
one the denoiser is built on -- the speckle is zero-mean in CHROMA over a neighbourhood, so
box-averaging in LINEAR light recovers the true local colour.  This downsamples 4x first
and only then asks how saturated the result is.

    CAUSTIC       cells at least CUT x the bare-cap level (default 2x)
    coverage      what fraction of the cap those cells are -- a thin filigree of threads
                  and a broad pool can have identical peak brightness and read nothing
                  alike, and this is the number that separates them
    sat           excess-weighted mean of (max-min)/max over the caustic cells; 0 = white
    peak          brightest single pixel, in multiples of the bare-cap level

AND IT MEASURES THE FLOAT SIDECAR, NOT THE PNG.  Every render here passes ftrace's `-hdr`
and the metering reads the `.pfm`.  This is not a refinement: an 8-bit sRGB PNG clamps at
white, a caustic is by definition the brightest thing in frame, and at the clip point all
three channels are EQUAL -- so the tone map destroys the hue and the peak ratio that this
rig exists to measure.  Every number this file printed before 2026-08-04 came through that
clamp and understates the brightest pieces worst: the winning axicon re-measures at
peak 14.68x / sat 0.355 / spread 0.237 where the PNG had said 5.91x / 0.320 / 0.212.

Usage:
    python scraps/_gemsweep.py piece <name> [drop ...]     orb | gyroid<k> | klein
    python scraps/_gemsweep.py k <drop> [k ...]            gyroid lattice frequency
"""
import subprocess, sys, os, math, re

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _pfm import Linear, scatter, fan, fmt                                          # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
os.chdir(ROOT)

CAP_Y = 0.85
CX, CZ = 3.0, 3.0
HALF = 1.75             # half-width of the metered patch, metres
# 480/600 is the SWEEP setting -- cheap enough to run a dozen geometries.  It is NOT enough to
# adjudicate a close call: at 480 with a 4x box the metered patch is 120x120 = 14400 cells, so
# a 0.13%-coverage caustic is 19 of them and `fan` (which needs 20) comes back unmeasurable.
# `GEMRES=960 GEMSPP=1200` for a finalist; cells go up 4x and the render cost about 8x.
RES = int(os.environ.get('GEMRES', '480'))
SPP = int(os.environ.get('GEMSPP', '600'))
DOWN = 4                # box factor that averages the hero-wavelength speckle away
# A cell is "caustic" at this multiple of the bare cap.  2.0 is the right bar for a LENS,
# but it hides a whole class of piece: a prism deviates and disperses without CONVERGING, so
# its coloured band never gets above ~1x the bare sunlight and scores a flat zero here.  Set
# GEMCUT=1.15 to meter that class instead.
CUT = float(os.environ.get('GEMCUT', '2.0'))
EYE = 8.0

# The glass every piece is cut from.  `GEMIOR=glass:SF10` re-runs any sweep in a denser flint:
# what splays a caustic across the spectrum is the DISPERSION, not the index, and by Abbe
# number SF10 (V_d 28.5) splays 1.5x as far as the scene's crystal/F2 (36.3) and 3.2x as far
# as BK7 (64.1).  Geometry sweeps have to be RE-RUN per glass rather than compared across
# them: a denser glass also deviates harder, so it moves the ring focus and the optimum cone
# angle and drop are no longer the same numbers.
IOR = os.environ.get('GEMIOR', 'glass:crystal')

HEAD = """\
# generated by scraps/_gemsweep.py -- do not edit
material "capwhite" {{ type diffuse  reflect whitewall 0.30 }}
material "glass"    {{ type dielectric  ior {ior} }}
quad {{ origin 0 {capy} 0   u 0 0 6   v 6 0 0   material capwhite }}
"""

TAIL = """\
light sun {{ dir -0.1470 0.7071 0.6916   angle 0.53   spd blackbody 5800   intensity 9.2649e-14 }}
camera "top" {{
    eye {cx} {eye} {cz}   look_at {cx} {capy} {cz}   up 0 0 -1   fov_y {fov}
    mode D
    film {{ res {res} {res}   exposure 0.25 }}
}}
"""

GYROID = """\
isosurface "piece" {{
    material glass
    intersect {{
        function {{
            translate {cx} {cy} {cz}
            expr "{ab}(sin({k}*x)*cos({k}*y) + sin({k}*y)*cos({k}*z) + sin({k}*z)*cos({k}*x)) - {t}"
        }}
        sphere {{ center {cx} {cy} {cz}   radius 0.50 }}
    }}
    contained_by {{ min {x0} {y0} {z0}   max {x1} {y1} {z1} }}
    max_gradient {mg}
}}
"""

ORB = 'sphere {{ center {cx} {cy} {cz}   radius 0.5   material glass }}\n'

# The SAME lattice, but clipped to an AXICON instead of to a ball.  This is the one shape
# that could settle the scene's design question without giving anything up: if the gyroid's
# outer boundary being a table-over-cone is enough to throw the axicon's coloured ring, then
# the crystal piece can stay a gyroid at the gold piece's pitch (the complementary-lattice
# statement survives) AND become the scene's colour source.  The doubt is real and is why it
# has to be rendered: the clip only sets the FIRST surface a ray meets, and behind it are the
# same internal sheets that make a gyroid a diffuser.
GYCONE = """\
isosurface "piece" {{
    material glass
    function {{
        translate {cx} {cy} {cz}
        expr "max({ab}(sin({k}*x)*cos({k}*y) + sin({k}*y)*cos({k}*z) + sin({k}*z)*cos({k}*x)) - {t},
                  max(sqrt(x*x + z*z) - {ck}*({h} + y), max(-y - {h}, y - {h})))"
    }}
    contained_by {{ min {x0} {y0} {z0}   max {x1} {y1} {z1} }}
    max_gradient {mg}
}}
"""

# The SAME solid network clipped to a BOX instead of a ball -- specifically a flat SLAB,
# half-extents (0.50, hy, 0.50): the scene ball's footprint, squashed in y.
#
# The hypothesis is not silly, and it is the same one that made SOLID beat SHELL: a slab
# presents a LARGER aperture to a near-overhead sun (1.00 m^2 of plan area against the
# ball's 0.785) while cutting the vertical path length, so fewer internal sheets are crossed
# and less of the light is diffused away.  Against it: `contained_by` seals a clip with the
# piece's own material, so a box clip caps the piece with FLAT, HORIZONTAL, PARALLEL faces
# -- a plane-parallel plate, which displaces a beam but cannot converge it -- where the
# sphere clip leaves a curved (lens) envelope.  That the drop sweep found a sharp optimum at
# 0.90 m is evidence the envelope is doing real focusing work, and a slab throws it away.
#
# Which effect dominates is not derivable, hence this.  `slab<k>[/hy]`, default hy = 0.125
# (x:y:z = 1 : 1/4 : 1).  Sweep hy to see whether thinning helps or hurts monotonically --
# one number at one thickness cannot tell those apart.
SLAB = """\
isosurface "piece" {{
    material glass
    function {{
        translate {cx} {cy} {cz}
        expr "max({ab}(sin({k}*x)*cos({k}*y) + sin({k}*y)*cos({k}*z) + sin({k}*z)*cos({k}*x)) - {t},
                  max(max(abs(x) - {hx}, abs(y) - {hy}), abs(z) - {hz}))"
    }}
    contained_by {{ min {x0} {y0} {z0}   max {x1} {y1} {z1} }}
    max_gradient {mg}
}}
"""

# --- LATERALLY dispersing shapes ---------------------------------------------------------
# The orb and every gyroid measured above are near-white for the same reason: a ball lens
# disperses only LONGITUDINALLY.  Every wavelength lands on the same axis, just at a slightly
# different depth, so at the cap they overlap into one disc.  Colour needs the focus to move
# SIDEWAYS, which means surfaces that are not parallel and not concentric.  These are the
# three canonical ways to do that, and the only honest way to rank them is to render them.

# A triangular PRISM -- the textbook lateral disperser.  Written as one field so a single
# transform orients the whole piece: max() of the three edge half-planes (base at y=-r,
# apex at y=+2r on the z=0 axis, inradius r) with the axial slab |x| < L.  All four normals
# are unit, so the field is Lipschitz-1 and max_gradient 2 is generous.
#
# `yaw` puts the prism's AXIS perpendicular to the sun's azimuth, which is what makes the
# dispersion plane vertical: the sun travels (0.147, -0.707, -0.692), so its horizontal
# heading is (0.208, -0.978) and the perpendicular is (0.978, 0, 0.208) = yaw 12 deg.
# `roll` then spins the triangle about that axis, and there is no closed form worth trusting
# for the best value (the deviation is ~48 deg at minimum for F2 at a 60 deg apex, but which
# face the sun enters, and whether the exit face TIRs instead, both flip with roll), so it
# is swept.
#
# NOTE: `rotate` is NOT a valid key inside a `function` block -- the loader warns
# ("unknown key 'rotate'") and carries on, so a rotated field silently renders unrotated and
# a whole roll sweep comes back as six identical rows.  Only `translate` composes there.
# Rather than wrap the isosurface in a `group { rotate }` (legal, but it makes the map
# non-positive-diagonal, which flips `im.boxOriented` and buys oriented-box clipping), the
# planes are rotated ALGEBRAICALLY: a half-space n.p <= d under p = R q is (R^T n).q <= d,
# so the four normals are just pre-rotated in Python and emitted as numbers.  Exact, and it
# needs no transform support at all.
PRISM = """\
isosurface "piece" {{
    material glass
    function {{
        translate {cx} {cy} {cz}
        expr "max(max(max({n0}, {n1}), {n2}), {n3})"
    }}
    contained_by {{ min {x0} {y0} {z0}   max {x1} {y1} {z1} }}
    max_gradient 2
}}
"""


def _half(n, d):
    """`n.p - d` as an expression string, for a unit normal n."""
    t = ' + '.join(f'{c:+.5f}*{v}' for c, v in zip(n, 'xyz') if abs(c) > 1e-6)
    return f'({t} - {d})'


def _rot(n, roll, yaw):
    """Rotate a normal by roll about +x, then yaw about +y (the object's own order)."""
    cr, sr = math.cos(math.radians(roll)), math.sin(math.radians(roll))
    x, y, z = n[0], n[1] * cr - n[2] * sr, n[1] * sr + n[2] * cr
    cy_, sy = math.cos(math.radians(yaw)), math.sin(math.radians(yaw))
    return (x * cy_ + z * sy, y, -x * sy + z * cy_)


GEM = """\
isosurface "piece" {{
    material glass
    function {{
        translate {cx} {cy} {cz}
        expr "{e}"
    }}
    contained_by {{ min {x0} {y0} {z0}   max {x1} {y1} {z1} }}
    max_gradient 2
}}
"""


def gem_body(R, crown, pav, table_h, d, nmain=8, ngirdle=16):
    """A round BRILLIANT cut as an intersection of half-spaces.

    This is the shape the cone sweep points at, built the way the real object is built: a
    flat TABLE on top and a faceted conical PAVILION below.  That combination is a faceted
    axicon -- light enters the table undeviated, and every pavilion facet is a prism at the
    same tilt, so the exit deviation is constant (a line focus, hence bright) while the
    dispersion is a prism's (hence coloured).  It is not a coincidence that this is the cut
    the trade evolved for "fire".

    Standard round-brilliant proportions, all measured from the girdle plane at y=0 with
    girdle radius R: crown angle 34.5 deg, pavilion angle 40.75 deg, table 53% of the girdle
    diameter.  A facet whose plane makes angle t with the horizontal has outward normal at t
    from +y, i.e. n = (sin t cos a, cos t, sin t sin a), and passing it through the girdle
    circle fixes d = R sin t.  The crown apex would then sit at R tan(34.5) = 0.687 R and the
    pavilion culet at -R tan(40.75) = -0.863 R (the textbook 43.1% of diameter); the table
    plane cuts the crown at table_h, leaving a table radius of R(1 - table_h/(R tan crown)).
    Every normal is unit, so the field is Lipschitz-1 and max_gradient 2 is generous.
    """
    ct, pt = math.radians(crown), math.radians(pav)
    planes = [((0.0, 1.0, 0.0), table_h)]
    for i in range(ngirdle):                       # girdle: a polygonal waist
        a = 2 * math.pi * i / ngirdle
        planes.append(((math.cos(a), 0.0, math.sin(a)), R))
    for i in range(nmain):                         # crown bezels
        a = 2 * math.pi * i / nmain
        planes.append(((math.sin(ct) * math.cos(a), math.cos(ct), math.sin(ct) * math.sin(a)),
                       R * math.sin(ct)))
    for i in range(nmain):                         # pavilion mains, offset half a facet
        a = 2 * math.pi * (i + 0.5) / nmain
        planes.append(((math.sin(pt) * math.cos(a), -math.cos(pt), math.sin(pt) * math.sin(a)),
                       R * math.sin(pt)))
    e = _half(planes[0][0], planes[0][1])
    for n, dd in planes[1:]:
        e = f'max({e}, {_half(n, dd)})'
    return GEM.format(e=e, **d)


def facet_body(n, R, h, pav, d):
    """A FACETED axicon: flat table on top, n flat pavilion facets below, all at `pav`.

    The smooth cone wins the caustic sweep but from the scene's low camera (11 deg above the
    horizon) a 45 deg cone is 2x as wide as it is tall and foreshortens into a squat glass
    wedge -- optically right, visually mute.  Every facet of this is at the SAME tilt as the
    cone it replaces, so each is still a prism at the axicon's angle and the optics should
    survive; what changes is that the ring focus is sampled at n discrete azimuths instead of
    continuously, which could either concentrate the cusps or scatter them.  Not derivable --
    measured.

    A pavilion facet at angle t from horizontal has outward normal (sin t cos a, -cos t,
    sin t sin a), and passing it through the girdle circle (radius R at height h) fixes
    d = R sin t - h cos t.
    """
    pt = math.radians(pav)
    planes = [((0.0, 1.0, 0.0), h)]
    for i in range(n):
        a = 2 * math.pi * i / n
        planes.append(((math.sin(pt) * math.cos(a), -math.cos(pt), math.sin(pt) * math.sin(a)),
                       R * math.sin(pt) - h * math.cos(pt)))
    e = _half(planes[0][0], planes[0][1])
    for nn, dd in planes[1:]:
        e = f'max({e}, {_half(nn, dd)})'
    return GEM.format(e=e, **d)


def prism_body(roll, yaw, r, L, d):
    # base at y=-r, two sloped faces meeting at an apex on the z=0 axis, axis along x
    faces = [((0.0, -1.0, 0.0), r), ((0.0, 0.5, 0.86603), r), ((0.0, 0.5, -0.86603), r),
             ((1.0, 0.0, 0.0), L)]
    ns = {f'n{i}': _half(_rot(n, roll, yaw), dd) for i, (n, dd) in enumerate(faces)}
    # the slab needs BOTH sides; fold the -x half-space into the tightest of the three
    ns['n3'] = f'max({ns["n3"]}, {_half(_rot((-1.0, 0.0, 0.0), roll, yaw), L)})'
    return PRISM.format(**ns, **d)

# An ELLIPSOID -- an astigmatic lens.  Its two principal curvatures focus at different
# depths, so instead of a point there are two perpendicular line foci, and off-axis the
# spectrum smears ALONG those lines rather than stacking behind itself.  Written with the
# sqrt so the field is a near-distance and the gradient is ~1/min(a,b,c).
ELLIP = """\
isosurface "piece" {{
    material glass
    function {{
        translate {cx} {cy} {cz}
        expr "sqrt(x*x/{a2} + y*y/{b2} + z*z/{c2}) - 1"
    }}
    contained_by {{ min {x0} {y0} {z0}   max {x1} {y1} {z1} }}
    max_gradient {mg}
}}
"""

# A glass TORUS -- a ring lens.  Every part of it is off-axis by construction, and the
# caustic of a ring is a ring, so the spectrum has somewhere to spread radially instead of
# piling up on one point.  Native primitive, so no field conditioning to worry about.
TORUS = """\
isosurface "piece" {{
    material glass
    torus {{ translate {cx} {cy} {cz}   rotate {roll} {yaw} 0   major {maj}   minor {mnr} }}
}}
"""

# A CONE (axicon).  A cone refracts every ray by the SAME angle regardless of where it hits,
# so it makes a line focus, not a point -- and dispersion spreads that line into a graded
# smear.  Apex up, opening downward, half-angle from the slope k.
CONE = """\
isosurface "piece" {{
    material glass
    function {{
        translate {cx} {cy} {cz}
        expr "max(sqrt(x*x + z*z) - {k}*({h} {sgn} y), max(-y - {h}, y - {h}))"
    }}
    contained_by {{ min {x0} {y0} {z0}   max {x1} {y1} {z1} }}
    max_gradient 3
}}
"""

# The SAME axicon, but cut so it READS as a gem: pavilion cone, straight GIRDLE band, and
# (optionally) a crown rising to a table.  The user asked for the scene's upside-down cone to
# be "shaped more like a diamond", and the honest answer to "which is better for caustics" is
# already on file -- a round brilliant loses 5x on coverage and 4x on peak because its 40.75
# deg pavilion TIRs the fire back up at the viewer.  But that verdict is about the PAVILION
# angle, and a gem's silhouette is mostly the girdle line.  So this shape keeps the winning
# 45 deg conical exit face EXACTLY as it is and only adds cuts ABOVE the girdle plane:
#
#   girdle  a straight cylinder of height g on top of the cone.  Predicted free: a ray that
#           enters the flat table crosses no interface until the cone, so it arrives there on
#           the same line it always did, just starting g higher.  Only the rim is touched,
#           because the sun comes in at 45 deg and a band that tall shades / admits a strip of
#           it.  "Predicted free" is why it is MEASURED and not simply asserted.
#   crown   the expensive part, and the one worth a number: a crown facet at angle c refracts
#           a vertical ray inward by c - asin(sin c / n) (15.6 deg for c=34.5 in SF10), so the
#           whole annulus outside the table hits the cone at a different incidence and either
#           lands somewhere else or TIRs.  With table fraction f that annulus is 1 - f^2 of
#           the aperture -- 44% at f=0.75, 72% at a true brilliant's f=0.53.  Sweeping c and f
#           is the only way to find out how much gem silhouette the caustic will pay for.
#
# `gcone[g][/crown/tablefrac]`, e.g. `gcone0.08` (girdle only) or `gcone0.08/34.5/0.75`.
GCONE = """\
isosurface "piece" {{
    material glass
    function {{
        translate {cx} {cy} {cz}
        expr "{e}"
    }}
    contained_by {{ min {x0} {y0} {z0}   max {x1} {y1} {z1} }}
    max_gradient 3
}}
"""


def gcone_body(g, crown, tf, d, R=0.56, h=0.28, ngird=0):
    """Field for the girdled axicon.  R is the girdle radius, h the cone's half-height.

    The solid is {r <= Rad(y)} between two end slabs, and Rad is the MIN of the three
    surfaces of revolution -- pavilion, girdle, crown -- which is exactly how the shape is
    described in words.  The pavilion term (h + y) is the scene's current field verbatim, so
    a `gcone` with g=0 and no crown is bit-identical to `vcone1.0` and can be used as the
    sweep's own control.

    Gradients: the pavilion contributes sqrt(2), the girdle 1, the crown sqrt(1 + cot^2 c)
    (1.77 at c=34.5, 2.92 at c=20), so max_gradient 3 covers the whole family.
    """
    yg = h + g                                     # top of the straight girdle band
    if crown > 0 and tf < 1.0:
        rt = tf * R
        cot = 1.0 / math.tan(math.radians(crown))
        yt = yg + (R - rt) / cot
        rad = f'min(min({h} + y, {R}), {R} - {cot:.6f}*(y - {yg:.6f}))'
    else:
        yt = yg
        # NOTE the parens on the bare-cone form: this is substituted as `sqrt(..) - {rad}`, so
        # an unparenthesised `0.28 + y` silently parses as `(sqrt(..) - 0.28) + y` and renders
        # a completely different solid.  (The `min(...)` form is safe only because the comma
        # already brackets it.)
        rad = f'min({h} + y, {R})' if ngird <= 0 else f'({h} + y)'
    e = f'max(sqrt(x*x + z*z) - {rad}, max(-y - {h}, y - {yt:.6f}))'
    if ngird > 0:
        # A FACETED girdle: n flat vertical chords instead of a cylinder.  This is the one
        # gem cut that is optically free by construction -- a vertical facet's normal is
        # horizontal, so it cannot deviate the descending aperture at all; only the rim rays
        # that would have grazed the cylinder see it.  What it buys is the read: sixteen
        # separate specular glints along the waist is the single most diamond-like cue the
        # piece can carry, and the scene's camera sits 11 deg above the horizon, looking
        # straight at that band.
        #
        # The planes are set at d = R cos(pi/n) so the polygon's CORNERS sit at exactly R and
        # meet the cone's rim flush -- pushing them out to R instead would leave the corners
        # overhanging the pavilion by 1 cm.  And they are applied only ABOVE the girdle plane,
        # as `min(P, y - h)`: below it that term goes negative and imposes nothing, so the
        # conical exit face -- the thing that actually makes the caustic -- is untouched.
        dd = R * math.cos(math.pi / ngird)
        P = None
        for i in range(ngird):
            a = 2 * math.pi * i / ngird
            t = _half((math.cos(a), 0.0, math.sin(a)), f'{dd:.6f}')
            P = t if P is None else f'max({P}, {t})'
        e = f'max({e}, min({P}, y - {h}))'
    return GCONE.format(e=e, **d)


# The Klein bottle is 0.60 m tall with its FOOT at the origin, so `drop` here is the
# height of its foot above the cap -- 0 is the scene's standing pose.
KLEIN = """\
mesh "piece" {{
    file "meshes/klein_bottle_full.obj"
    translate {cx} {cy} {cz}   rotate 0 -12 0   scale 0.02
    material glass
}}
"""


# Puts a piece's local +x axis PERPENDICULAR to the sun's azimuth, so the dispersion plane
# stands vertical.  A yaw of t about +y sends (1,0,0) to (cos t, 0, -sin t), and the sun's
# horizontal heading is (0.208, -0.978); the dot product vanishes at t = -12, not +12.
SUN_YAW = -12.0


def body(piece, cy):
    # HALF-SIZE OF `contained_by`, and it is NOT cosmetic: contained_by is a hard clip, not a
    # hint, so the default 0.5 quietly SHAVES THE CORNERS off any piece wider than a 1 m cube.
    # `vcone1.0` is exactly such a piece -- its girdle radius is 0.56 -- so every axicon number
    # this rig has printed was measured on a cone with four flats cut into its rim.  That is
    # fine for ranking shapes against each other as long as they all share the box, which is
    # why the default is left alone; use `GEMBOX=0.7` to measure the unclipped article, and
    # re-run the control in the same invocation so the comparison stays honest.
    B = float(os.environ.get('GEMBOX', '0.5'))
    d = dict(cx=CX, cy=cy, cz=CZ, yaw=SUN_YAW,
             x0=CX - B, y0=cy - B, z0=CZ - B,
             x1=CX + B, y1=cy + B, z1=CZ + B)
    if piece.startswith('gcone'):
        # `gcone[g][/crown/tablefrac]` -- the scene's axicon with a girdle (and maybe a crown).
        parts = piece[5:].split('/')
        g = float(parts[0]) if parts and parts[0] else 0.08
        crown = float(parts[1]) if len(parts) > 1 and parts[1] else 0.0
        tf = float(parts[2]) if len(parts) > 2 and parts[2] else 1.0
        ng = int(parts[3]) if len(parts) > 3 and parts[3] else 0
        return gcone_body(g, crown, tf, d, ngird=ng)
    if piece == 'orb':
        return ORB.format(**d)
    if piece == 'klein':
        return KLEIN.format(**d)
    # --- the lateral dispersers ---
    if piece.startswith('facet'):
        # `facet<n>` -- the scene's axicon (R 0.56, table at +0.28, 45 deg) cut into n facets.
        return facet_body(int(float(piece[5:] or 12)), 0.56, 0.28, 45.0, d)
    if piece.startswith('gem'):
        # `gem[R][/crown/pav]` -- a round brilliant of girdle radius R (default 0.40) at the
        # standard 34.5 / 40.75 deg angles.  The table height is DERIVED, not guessed: a table
        # that is 53% of the girdle diameter has radius 0.53R, and the crown facet plane puts
        # radius R(1 - h/(R tan crown)) at height h, so h = 0.47 R tan(crown) = 0.323 R.
        arg = piece[3:]
        parts = arg.split('/') if arg else []
        R = float(parts[0]) if parts and parts[0] else 0.40
        crown = float(parts[1]) if len(parts) > 1 else 34.5
        pav = float(parts[2]) if len(parts) > 2 else 40.75
        return gem_body(R, crown, pav, 0.47 * R * math.tan(math.radians(crown)), d)
    if piece.startswith('prism'):
        return prism_body(float(piece[5:] or 0.0), SUN_YAW, 0.20, 0.45, d)
    if piece.startswith('ellip'):
        # `ellip<b>`: a vertical-axis spheroid, semi-axes 0.50 x b x 0.50.  It needs no
        # rotation to be off-axis -- the sun is already 45 deg off its symmetry axis, which
        # is the whole point.  b < 0.50 is oblate (a squashed lens), b > 0.50 prolate.
        a = c = 0.50
        b = float(piece[5:] or 0.22)
        return ELLIP.format(a2=a * a, b2=b * b, c2=c * c,
                            mg=int(2.0 / min(a, b, c)) + 1, **d)
    if piece.startswith('torus'):
        return TORUS.format(roll=float(piece[5:] or 0.0), maj=0.34, mnr=0.15, **d)
    # `cone<k>` is apex UP (flat base down), `vcone<k>` apex DOWN (flat face up, the classic
    # axicon orientation).  Which is better is not obvious: apex-up presents a sloped face to
    # the sun and a flat one to the cap, apex-down the reverse, and the exit face is where
    # total internal reflection decides whether any light gets out at all.
    # `<k>/<h>` sets the SIZE as well as the slope (half-height h, top radius 2kh).  Size is
    # not a free parameter here: the cusps land at a distance that scales with the piece, so
    # it is what decides how wide a cap the exhibit needs.
    if piece.startswith('vcone'):
        k, _, hh = piece[5:].partition('/')
        return CONE.format(k=float(k or 0.9), h=float(hh or 0.28), sgn='+', **d)
    if piece.startswith('cone'):
        k, _, hh = piece[4:].partition('/')
        return CONE.format(k=float(k or 0.9), h=float(hh or 0.28), sgn='-', **d)
    # `gyroid<k>`  = the scene's SHELL form, |G| < 0.55: a labyrinth of thin curved
    #                glass sheets, so a ray crosses many of them.
    # `solid<k>[/t] = one of the two interpenetrating SOLID networks, G < t: chunky
    #                struts with one entry and one exit, i.e. an actual optical body.
    if piece.startswith('gycone'):
        # `gycone<k>` -- the SOLID network (G < 0) clipped to the winning 45 deg axicon.
        k = float(piece[6:] or 10.0)
        return GYCONE.format(ab='', k=k, t=0.0, ck=1.0, h=0.28, mg=int(4 * k), **d)
    if piece.startswith('slab'):
        # `slab<k>[/hy]` -- the SOLID network clipped to a flat BOX rather than a ball.
        # hx = hz = 0.50 matches the scene ball's radius exactly, so the only variable
        # against the `solid<k>` control is the shape of the envelope and the y extent.
        arg = piece[4:]
        k, _, hy = arg.partition('/')
        return SLAB.format(ab='', k=float(k or 10.0), t=0.0,
                           hx=0.50, hy=float(hy or 0.125), hz=0.50,
                           mg=int(4 * float(k or 10.0)), **d)
    if piece.startswith('fin'):
        # `fin<k>[/hz]` -- the SAME box clip thinned in DEPTH instead of in height: a plate
        # standing on edge, hx = hy = 0.50 with hz the variable.  This is NOT `slab` rotated,
        # and the difference is the whole point: the sun is near-overhead, so `slab` thins the
        # axis the light travels ALONG (a plane-parallel plate presented square to the beam),
        # while `fin` thins an axis the light travels ACROSS and keeps the full 1.0 m of
        # network for it to travel through.  Whether that beats the slab's larger plan
        # aperture is exactly the thing that is not derivable.
        # NOTE the height constraint: hy = 0.50 hangs the piece 0.50 m below its centre, so
        # any drop below ~0.60 buries it in the cap.  Sweep drop from 0.70 up.
        arg = piece[3:]
        k, _, hz = arg.partition('/')
        return SLAB.format(ab='', k=float(k or 10.0), t=0.0,
                           hx=0.50, hy=0.50, hz=float(hz or 0.3125),
                           mg=int(4 * float(k or 10.0)), **d)
    if piece.startswith('plate'):
        # `plate<k>/<f>[/<H>]` -- the requested horizontal:depth:vertical = 1 : f : 1 shape,
        # but with the OVERALL SCALE freed.  `fin` is this shape locked at H = 0.50 (a full
        # 1.0 m tall plate) and it loses everywhere, for a reason that is about size and not
        # about proportion: the sun is near-overhead, so it is the VERTICAL extent that sets
        # how much network the light traverses, and the earlier `slab` sweep already located
        # the optimum of that at ~0.625 m.  A `fin` pins it at 1.0 m, which over-diffuses.
        # Shrinking the whole 1 : f : 1 body until its vertical lands on 0.625 m keeps the
        # proportion exactly as asked while restoring the path length that actually focuses.
        # Note the lattice is NOT scaled with the body -- `k` is in world units -- so this is
        # a smaller window onto the same gyroid, not a shrunken copy of the piece.
        arg = piece[5:]
        k, _, rest = arg.partition('/')
        f, _, H = rest.partition('/')
        H = float(H or 0.3125)
        return SLAB.format(ab='', k=float(k or 10.0), t=0.0,
                           hx=H, hy=H, hz=float(f or 0.3125) * H,
                           mg=int(4 * float(k or 10.0)), **d)
    if piece.startswith('solid'):
        arg = piece[5:]
        k, _, t = arg.partition('/')
        return GYROID.format(ab='', k=float(k), t=float(t or 0.0),
                             mg=int(4 * float(k)), **d)
    k = float(piece[6:]) if len(piece) > 6 else 13.0
    return GYROID.format(ab='abs', k=k, t=0.55, mg=int(4 * k), **d)


def render(piece, drop, tag):
    cy = CAP_Y + drop
    fov = 2 * math.degrees(math.atan(HALF / (EYE - CAP_Y)))
    txt = (HEAD.format(capy=CAP_Y, ior=IOR) + body(piece, cy)
           + TAIL.format(cx=CX, cz=CZ, eye=EYE, capy=CAP_Y,
                         fov=f'{fov:.4f}', res=RES))
    sf = 'scraps/_gemsweep.ftsl'
    open(sf, 'w', encoding='utf-8').write(txt)
    # Piece names carry '/' and '.' (e.g. `gcone0.08/34.5/0.75`); neither belongs in a path.
    tag = re.sub(r'[^A-Za-z0-9_]+', '_', tag)
    png = f'scraps/_gemsweep_{tag}.png'
    # Parse first and FAIL LOUDLY on a loader warning.  An unknown key inside a block is a
    # warning, not an error, so a mis-authored piece renders as something else entirely --
    # this rig once returned six identical rows for six roll angles because `rotate` is not
    # accepted inside `function` and every one of them rendered unrotated.
    chk = subprocess.run(['./ftrace.exe', '-in', sf, '-parseonly'],
                         capture_output=True, text=True)
    for line in (chk.stdout + chk.stderr).splitlines():
        if 'warning' in line.lower():
            raise SystemExit(f'FTSL warning building `{piece}` -- fix it, do not measure it:'
                             f'\n  {line.strip()}')
    # `-hdr` writes a float PFM beside the PNG and that is what gets METERED.  The PNG is
    # 8-bit sRGB with a hard clamp, and a caustic is the brightest thing in frame, so its
    # core prints as #FFFFFF with all three channels EQUAL -- the tone map destroys the hue
    # and the peak ratio before this rig can see them.  Every number this file printed
    # before 2026-08-04 was taken through that clamp and understates bright pieces most.
    #
    # `-fireflies` came with it and is NOT optional once the clamp is gone.  Mode D carries
    # one hero wavelength per sample, so a rare specular-caustic path deposits an enormous
    # MONOCHROMATIC spike; the PNG's clamp used to flatten those to white and was, by
    # accident, the only outlier rejection this rig had.  Metering the raw float instead
    # returned peak 1389x / sat 0.838 for the orb and peak 1214x / spread 0.594 for the
    # solid gyroid -- the gyroid, which throws no caustic at all, "winning" on three
    # firefly cells.  `-fireflies 3` clamps an isolated outlier to 3x its second-brightest
    # neighbour with its hue preserved, which removes the spikes without touching a real
    # caustic (a caustic is never isolated -- its neighbours are bright too).
    # `GEMDEV=cpu` forces the CPU path.  Not a preference: when another process on the machine
    # has the card, ftrace's megakernel spills its per-thread local memory to host RAM over
    # PCIe and a 1-spp chunk takes minutes instead of 0.15 s.  Because every `-interval` write
    # happens BETWEEN chunks, such a render produces no output at all -- it looks hung, and a
    # sweep left overnight comes back with nothing.  `nvidia-smi` is the tell (card ~100% used
    # by something that is not ftrace).
    dev = os.environ.get('GEMDEV', '')
    # DELETE the sidecar first, so a run that dies cannot leave a half-converged `.pfm` on
    # disk for someone to meter by hand later.  `-interval` writes a partial image every 30 s
    # and `check=True` only protects the caller who is inside this function -- it did not stop
    # a killed 16-facet render's 30-second snapshot from being metered and published as a
    # 600-spp number (peak 29.71x where the real answer is 32.41x, sat 0.470 where it is
    # 0.428).  An absent file is an honest error; a stale one is a wrong table.
    for stale in (png, png[:-4] + '.pfm'):
        try:
            os.remove(stale)
        except OSError:
            pass
    cmd = ['./ftrace.exe', '-in', sf, '-spp', str(SPP), '-o', png, '-hdr',
           '-fireflies', '3', '-window', '-interval', '30']
    if dev:
        cmd += ['-device', dev]
    # stdout is muted (per-frame banner spam) but stderr is NOT, and that is deliberate: the
    # `[gpu-stall]` watchdog warns on stderr, and routing it to DEVNULL as this used to do is
    # what made the starvation above invisible for a whole sweep.
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL)
    return png[:-4] + '.pfm'


def measure(png, label):
    im = Linear(png)
    w, h = im.w, im.h
    if im.clipped:
        print(im.banner())

    cells = []
    grid = []               # same cells, kept 2D, so a cell can be compared with its NEIGHBOURS
    for by in range(0, h - DOWN + 1, DOWN):
        row = []
        for bx in range(0, w - DOWN + 1, DOWN):
            acc = [0.0, 0.0, 0.0]
            hot = 0.0
            for y in range(by, by + DOWN):
                for x in range(bx, bx + DOWN):
                    p = im.at(x, y)
                    for c in range(3):
                        acc[c] += p[c]
                    hot = max(hot, 0.2126 * p[0] + 0.7152 * p[1] + 0.0722 * p[2])
            n = DOWN * DOWN
            # keep each cell's WORLD position too -- a metric that says a caustic exists but
            # not where it lands or how wide it is cannot be used to author a cap for it.
            # The camera looks straight down from (CX, EYE, CZ) with up = -z, so image right
            # is +x and image down is +z, over a square 2*HALF metres on a side.
            c = (tuple(a / n for a in acc),
                 CX + ((bx + DOWN / 2) / w - 0.5) * 2 * HALF,
                 CZ + ((by + DOWN / 2) / h - 0.5) * 2 * HALF,
                 hot)
            cells.append(c)
            row.append(c)
        grid.append(row)

    # SPIKE REJECTION AT THE CELL LEVEL, because `-fireflies 3` and the 4x box together are
    # NOT enough and the failure is worst exactly where the rig is trusted most.  Measured:
    # one geometry (`solid10`, drop 0.90) reported peak 3.00x / sat 0.182 / spread 0.014 at
    # 480px/600spp and peak 1179.42x / sat 0.844 / spread 0.672 at the 960px/1200spp setting
    # this file's own docstring prescribes for finalists -- same piece, same optics, garbage
    # numbers.  Raising resolution puts FEWER samples in each metered cell, so a single hero-
    # wavelength spike is diluted less by the box, and the finalist setting is therefore the
    # most contaminated one rather than the least.
    #
    # The discriminator is the one the sampler cannot fake, and it is already written down in
    # this file: A CAUSTIC IS NEVER ISOLATED -- its neighbours are bright too, because it is
    # an image of a continuous wavefront.  A firefly is one cell with ordinary cap all round
    # it.  So compare each cell with its SECOND-BRIGHTEST neighbour and drop it if it stands
    # more than SPIKE times above that.
    #
    # SECOND-BRIGHTEST, NOT MEDIAN, AND THE DIFFERENCE IS NOT COSMETIC -- the median version
    # of this test silently ate the best caustic in the scene.  The axicon's caustic is a
    # RING one or two cells wide, so a genuine ring cell has 8 neighbours of which only two
    # or three are also on the ring and the rest are bare cap; the median of that set is
    # BACKGROUND, and every cell of the ring then reads as an isolated spike.  Measured: the
    # median test threw away 263 cells from `vcone1.0` at drop 0.50 while keeping only 219 --
    # it was deleting more caustic than it measured.  The second-brightest neighbour is
    # background only if the cell really is alone, which is the actual definition being
    # tested; for any structure at least two cells long it is on the structure.  (This is
    # also exactly what ftrace's own `-fireflies` does, and for the same reason -- it clamps
    # to a multiple of the second-brightest neighbour, not to a neighbourhood average.)
    #
    # 8x is deliberately loose.  Real caustics climb by well under 2x from one cell to the
    # next even at their cusps (a 4x box is 1/120 of the frame, far coarser than any real
    # caustic gradient), while the spikes overshoot their neighbourhood by two to three
    # ORDERS of magnitude.  There is a wide gap between those, and sitting in the middle of
    # it means the threshold never has to be re-tuned per piece.
    # ...AND THE SAME TEST HAS TO BE RUN ON THE RAW PIXEL, NOT ONLY ON THE AVERAGED CELL.
    # This was a real bug in this file and it produced a real false result.  `peak` is read
    # from each cell's `hot` -- the brightest RAW pixel in the 4x4 block -- while the spike
    # test above only ever looked at the block's AVERAGE.  A 4x box dilutes a single-pixel
    # firefly 16-fold, so a spike big enough to dominate `peak` can sit a comfortable factor
    # below the 8x cell threshold and survive.  Measured: `fin10/0.125` at drop 0.90 reported
    # peak 84.34x / spread 0.437 and passed the cell test cleanly; histogramming the raw .pfm
    # showed exactly TWO pixels in 480x480 above 5x the median (85x and 1115x) with everything
    # else topping out near 2x.  That is not a caustic, it is two samples.
    #
    # So run the identical second-brightest-neighbour test a second time on `hot`, and take
    # the UNION of the two spike sets.  Union rather than a separate peak-only filter because
    # a pixel spike contaminates the cell's average too -- a 1000x pixel is still +60x on the
    # 16-pixel mean it lands in, which is plenty to move `sat` and `spread` as well.
    SPIKE = float(os.environ.get('GEMSPIKE', '8.0'))
    gh, gw = len(grid), len(grid[0]) if grid else 0
    lum_of = (lambda c: 0.2126 * c[0][0] + 0.7152 * c[0][1] + 0.0722 * c[0][2])
    hot_of = (lambda c: c[3])
    spikes = set()
    for j in range(gh):
        for i in range(gw):
            for key in (lum_of, hot_of):
                nb = sorted(key(grid[jj][ii])
                            for jj in range(max(0, j - 1), min(gh, j + 2))
                            for ii in range(max(0, i - 1), min(gw, i + 2))
                            if (ii, jj) != (i, j))
                if len(nb) >= 2 and key(grid[j][i]) > SPIKE * nb[-2]:
                    spikes.add((i, j))
                    break
    if spikes:
        cells = [c for j, row in enumerate(grid) for i, c in enumerate(row)
                 if (i, j) not in spikes]
    peak = max((c[3] for c in cells), default=0.0)

    lums = sorted(0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2] for c, _, _, _ in cells)
    bg = lums[len(lums) // 2]           # the bare sunlit cap dominates the frame

    wsum = satsum = 0.0
    n = 0
    chroma = []
    ctrl = []
    box = []
    for c, wx, wz, _ in cells:
        lum = 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]
        # CONTROL BAND: 1.0-1.2x the median is bare sunlit cap with no caustic on it, so its
        # chromatic scatter is this render's SPECKLE FLOOR.  It is not small and it is not
        # optional to know: `spread` cannot tell dispersed colour from random colour, and at
        # 600 spp with one hero wavelength per sample there is plenty of the latter.
        if bg <= lum < 1.2 * bg:
            s0 = c[0] + c[1] + c[2]
            if s0 > 1e-9:
                ctrl.append((1.0, c[0] / s0, c[2] / s0, wx, wz))
        if lum < CUT * bg:
            continue
        n += 1
        e = lum - bg
        mx, mn = max(c), min(c)
        satsum += e * ((mx - mn) / mx if mx > 1e-9 else 0.0)
        wsum += e
        s = c[0] + c[1] + c[2]
        if s > 1e-9:
            chroma.append((e, c[0] / s, c[2] / s, wx, wz))
        box.append((e, wx, wz))
    sat = satsum / wsum if wsum > 0 else 0.0
    cov = 100.0 * n / len(cells)

    # SPREAD -- the number `sat` cannot give you.  `sat` says how far the caustic is from
    # white; it says nothing about whether it is ONE tint or a rainbow, and a uniformly
    # amber patch and a red-to-blue fan can score the same.  So take each caustic cell's
    # chromaticity (r, b) = (R, B)/(R+G+B), find the excess-weighted centroid, and report
    # twice the weighted RMS radius about it.  A white or uniformly tinted caustic collapses
    # to a point plus sampler noise; a real spectrum is a long streak.
    # ... and `noise` / `fan` are what keep it honest: `spread` above the noise floor says the
    # colour is real, `fan` (how much of the chromaticity a quadratic in position explains)
    # says it is ARRANGED rather than just loud.  Both live in `_pfm.py` so this rig and
    # `_capchroma.py` score pieces on one implementation.
    spread, noise = scatter(chroma), scatter(ctrl)
    print(f'  {label:22s} peak {peak/bg:5.2f}x   coverage {cov:5.2f}%   '
          f'sat {sat:.3f}   spread {spread:.3f}   '
          f'noise {noise:.3f}/fan {fmt(fan(ctrl))}   fan {fmt(fan(chroma))}'
          f'{"" if not spikes else f"   [{len(spikes)} spike cells dropped]"}')
    if box:
        # WHERE the caustic lands and HOW BIG it is -- a metric that says one exists but not
        # where cannot be used to author a cap for it.  Reported as excess-weighted
        # quantiles, not a raw bounding box: a handful of stray sparkle cells out at the
        # frame edge trebled the raw box and made it useless.  5%..95% of the light.
        def span(i):
            v = sorted((q[i], q[0]) for q in box)
            tot = sum(q[1] for q in v)
            out, acc = [], 0.0
            for lim in (0.05, 0.95):
                for val, wt in v:
                    if acc >= lim * tot:
                        break
                    acc += wt
                out.append(val)
                acc = 0.0
            return out
        (x0, x1), (z0, z1) = span(1), span(2)
        cx_ = sum(q[0] * q[1] for q in box) / wsum
        cz_ = sum(q[0] * q[2] for q in box) / wsum
        # offsets are from the piece's own vertical axis, which is what a cap is authored
        # against -- "the core sits 0.19 m downwind of the column and is 0.5 m across".
        print(f'  {"":22s} core {cx_-CX:+.2f} {cz_-CZ:+.2f}   '
              f'90% of light in x {x0-CX:+.2f}..{x1-CX:+.2f} ({x1-x0:.2f} m)  '
              f'z {z0-CZ:+.2f}..{z1-CZ:+.2f} ({z1-z0:.2f} m)')
    return sat, cov, spread


if __name__ == '__main__':
    print(f'over a bare cap, {RES}x{RES} / {2*HALF:.1f} m, {SPP} spp, '
          f'{DOWN}x box, caustic = >{CUT:g}x cap\n')
    mode = sys.argv[1]
    if mode == 'piece':
        piece = sys.argv[2]
        for d in [float(a) for a in sys.argv[3:]] or [0.90]:
            measure(render(piece, d, f'{piece}_{int(d*100):03d}'),
                    f'{piece} drop {d:.2f}')
    elif mode == 'roll':
        # `roll <shape> <drop> [deg ...]` -- spin a lateral disperser about its axis. The
        # best roll is not derivable: which face the sun enters, and whether the exit face
        # total-internally-reflects instead of transmitting, both flip as it turns.
        shape, drop = sys.argv[2], float(sys.argv[3])
        for r in [float(a) for a in sys.argv[4:]] or [0, 30, 60, 90, 120, 150]:
            measure(render(f'{shape}{r:g}', drop, f'{shape}_r{int(r):03d}'),
                    f'{shape} roll {r:g}')
    elif mode == 'k':
        drop = float(sys.argv[2])
        for k in [float(a) for a in sys.argv[3:]] or [4, 6, 8, 10, 13]:
            measure(render(f'gyroid{k:g}', drop, f'k{int(k*10):03d}'),
                    f'gyroid k={k:g} d{drop:.2f}')
