"""The white-furnace rig: measure any BRDF's effective albedo against a known answer.

    python tools/furnace_rig.py [--spp 3000] [--device gpu] [--keep]

A closed enclosure of uniform radiance L has a property worth building a rig around: EVERY
energy-conserving BRDF inside it renders at exactly L. A mirror reflects the wall; a white
Lambertian receives irradiance pi*L and returns a*L. So `sphere / wall` IS the effective albedo of
whatever material the sphere carries, with no calibration constant to fit and no reference render
to compare against.

The script writes the scenes, renders them, and prints two blocks: the RIG VALIDATION (three
controls whose answers are known in advance) and then the results. Read the validation first. It is
there because this rig went wrong twice before it went right, and both failures produced
confident-looking numbers:

  * v1/v2 built the walls from `light area {}`. Those are NEE-only emitters with NO HITTABLE
    SURFACE, so a BSDF ray passes straight through into the void. A MIRROR in that box rendered as
    exactly 0.0000 -- the rig was blind to precisely the term being measured, and the missing energy
    read as a material bug.
  * The next version used real emissive geometry as ONE mesh, and rendered black: an emissive mesh
    whose triangles are not coplanar is silently re-oriented outward (see known-issues.md). Hence
    one `mesh` block per wall below -- that is a workaround, not a style choice.

The three controls (mirror -> 1.000, diffuse 1.0 -> 1.000, diffuse 0.5 -> 0.500) catch both.

Cited by `design.md`, `known-issues.md` and `TODO.md` for the coated-body numbers (0.323.0/0.324.0).
"""
import argparse
import io
import math
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, "tools"))

OUT = os.path.join("scraps", "_furnace")
PNG = os.path.join("png", "furnace")

# ------------------------------------------------------------------ the enclosure
HEAD = """# WHITE FURNACE -- generated by tools/furnace_rig.py; edit that, not this.
#
# Six inward-facing emissive walls, camera INSIDE. In a closed enclosure of uniform radiance L,
# every energy-conserving BRDF renders at exactly L, so sphere/wall is the effective albedo.
#
# Each wall is its OWN mesh block. One mesh holding all six renders the whole frame BLACK, because
# an emissive mesh whose triangles are not coplanar is silently re-oriented outward -- see
# known-issues.md, "an emissive mesh that is not PLANAR". Six blocks is the workaround.
camera "cam" {{ eye 0 0 0.88  look_at 0 0 0  up 0 1 0  fov_y 40  mode D  film {{ res 240 240 }} }}
material "wall" {{ type diffuse reflect 0.0  emit 1.0 }}
{walls}
"""

# probe material -> (label, expected value or None)
FDR = -1.440 / 2.25 + 0.710 / 1.5 + 0.668 + 0.0636 * 1.5          # 0.5967 at n = 1.5
S_ESC = 2.0 * 2.25 * (1.0 - math.sqrt(1.0 - 1.0 / 2.25))          # 1.1459
S_TIR = 2.0 / math.sqrt(1.0 - 1.0 / 2.25)                         # 2.6833


def aeff(a, tio=1.0, trt=1.0):
    return a * tio * (1.0 - FDR) / (1.0 - a * FDR * trt)


COAT = 'coat { reflectance fresnel roughness 0.06 }'
CASES = [
    # (tag, materials, label, expected, is_control)
    ("mir", 'material "probe" { type mirror reflect 1.0 }', "mirror", 1.0, True),
    ("v1", 'material "probe" { type diffuse reflect 1.0 }', "diffuse 1.0", 1.0, True),
    ("v05", 'material "probe" { type diffuse reflect 0.5 }', "diffuse 0.5", 0.5, True),
    ("cb", 'material "blk" { type diffuse reflect 0.0 }\n'
           'material "probe" { type layered ior 1.5 %s layer "blk" 1.0 }' % COAT,
     "coated BLACK body (measures the coat lobe F alone)", None, False),
    ("cw", 'material "wb" { type diffuse reflect 1.0 }\n'
           'material "probe" { type layered ior 1.5 %s layer "wb" 1.0 }' % COAT,
     "coated white 1.0", None, False),
    ("c05", 'material "gb" { type diffuse reflect 0.5 }\n'
            'material "probe" { type layered ior 1.5 %s layer "gb" 1.0 }' % COAT,
     "coated grey 0.5", None, False),
    ("abs", 'material "wb2" { type diffuse reflect 1.0 }\n'
            'material "probe" { type layered ior 1.5 '
            'coat { reflectance fresnel roughness 0.06 absorb 2000 depth 0.0001 } layer "wb2" 1.0 }',
     "coated white, absorbing coat (absorb 2000, depth 1e-4)", None, False),
]


def write_scenes():
    for d in (OUT, PNG):
        if not os.path.isdir(d):
            os.makedirs(d)
    walls = []
    for ax in range(3):
        for s in (-1, 1):
            fa = [a for a in range(3) if a != ax]
            ring = []
            for du, dv in ((-1, -1), (1, -1), (1, 1), (-1, 1)):
                p = [0.0, 0.0, 0.0]
                p[ax] = float(s); p[fa[0]] = float(du); p[fa[1]] = float(dv)
                ring.append(tuple(p))
            v0, v1, v2 = ring[0], ring[1], ring[2]
            e1 = [v1[k] - v0[k] for k in range(3)]
            e2 = [v2[k] - v0[k] for k in range(3)]
            n = (e1[1] * e2[2] - e1[2] * e2[1], e1[2] * e2[0] - e1[0] * e2[2],
                 e1[0] * e2[1] - e1[1] * e2[0])
            cen = [sum(p[k] for p in ring) / 4.0 for k in range(3)]
            if sum(n[k] * -cen[k] for k in range(3)) < 0:
                ring = ring[::-1]                                  # face INWARD
            nm = "wall_%s%s" % ("xyz"[ax], "n" if s < 0 else "p")
            io.open(os.path.join(OUT, nm + ".obj"), "w", encoding="utf-8", newline="\n").write(
                "# one inward-facing furnace wall (tools/furnace_rig.py)\n" +
                "".join("v %g %g %g\n" % p for p in ring) + "f 1 2 3\nf 1 3 4\n")
            walls.append('mesh "%s" { file "%s/%s.obj"  material wall }'
                         % (nm, OUT.replace(os.sep, "/"), nm))
    head = HEAD.format(walls="\n".join(walls))
    for tag, mats, _, _, _ in CASES:
        io.open(os.path.join(OUT, tag + ".ftsl"), "w", encoding="utf-8", newline="").write(
            head + mats + "\nsphere { center 0 0 0  radius 0.12  material probe }\n")


def render(tag, spp, device):
    exe = os.path.join(ROOT, "ftrace.exe")
    out = os.path.join(PNG, tag + ".png")
    subprocess.run([exe, "-in", os.path.join(OUT, tag + ".ftsl"), "-mode", "D",
                    "-device", device, "-spp", str(spp), "-hdr", "-o", out,
                    "-window-min", "-interval", "30"],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
    return out[:-4] + ".pfm"


def ratio(pfm):
    from grade_hdr import read_pfm
    a = read_pfm(pfm)

    def lum(sl):
        return float(0.2126 * a[sl][:, :, 0].mean() + 0.7152 * a[sl][:, :, 1].mean()
                     + 0.0722 * a[sl][:, :, 2].mean())
    return lum((slice(112, 128), slice(112, 128))) / lum((slice(4, 30), slice(4, 30)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spp", type=int, default=3000)
    ap.add_argument("--device", default="gpu")
    ap.add_argument("--keep", action="store_true", help="keep the generated scenes")
    args = ap.parse_args()

    write_scenes()
    vals = {}
    for tag, _, label, _, _ in CASES:
        print("  rendering %-4s (%s) ..." % (tag, label))
        vals[tag] = ratio(render(tag, args.spp, args.device))

    print("\nRIG VALIDATION -- the rig must already know these three, or nothing below counts:")
    ok = True
    for tag, _, label, exp, ctl in CASES:
        if not ctl:
            continue
        bad = abs(vals[tag] - exp) > 0.02
        ok = ok and not bad
        print("   %-12s %.4f   (must be %.3f)%s" % (label, vals[tag], exp, "   <-- FAIL" if bad else ""))
    print("   -> rig %s\n" % ("VALID, and it can see specular" if ok else
                              "BROKEN -- everything below is void"))

    f = vals["cb"]                       # the coat's own lobe, measured rather than assumed
    print("RESULTS -- prediction = F + (1-F) a_eff, with F MEASURED from the black-body case (%.4f):" % f)
    tio = math.exp(-2000.0 * 1e-4 * 2 * S_ESC)
    trt = math.exp(-2000.0 * 1e-4 * 2 * S_TIR)
    for tag, a, tio_, trt_ in (("cw", 1.0, 1.0, 1.0), ("c05", 0.5, 1.0, 1.0), ("abs", 1.0, tio, trt)):
        pred = f + (1.0 - f) * aeff(a, tio_, trt_)
        got = vals[tag]
        lbl = [c[2] for c in CASES if c[0] == tag][0]
        print("   %-46s %.4f   predicted %.4f   err %+.2f %%"
              % (lbl, got, pred, 100.0 * (got / pred - 1.0)))
    print("\n   The white body MUST read 1.000: a_eff(1) = 1, so a white body under a CLEAR")
    print("   lossless coat loses nothing. An absorbing coat is supposed to fall below it.")

    if not args.keep:
        for fn in os.listdir(OUT):
            os.remove(os.path.join(OUT, fn))
        os.rmdir(OUT)


if __name__ == "__main__":
    main()
