#!/usr/bin/env python3
"""Generate simple parametric test meshes as Wavefront OBJ.

Used to stress the renderer's BVH and mesh loader with thousands of triangles.
The geometry is emitted in a unit-ish scale centred at the origin; place it in a
scene with the loader's translate/scale.

Examples:
    python make_mesh.py torus  -o torus.obj  --nu 128 --nv 64
    python make_mesh.py sphere -o sphere.obj --subdiv 5
    python make_mesh.py torus  -o torus_smooth.obj --smooth      # emit `vn`

`--smooth` writes ANALYTIC per-vertex normals (`vn`) alongside the positions, which
the ftrace OBJ loader picks up automatically for smooth shading. It is opt-in, not
the default, because several checked-in scenes (scenes/group.ftsl, meshlight.ftsl,
triplanar.ftsl) and a known-issues repro use these meshes flat-shaded, and silently
smoothing them would change those renders.

Smooth normals also enable the `curv` pattern variable: mean curvature is derived
from the interpolated shading-normal field, so a flat-shaded mesh honestly reads 0
everywhere. Anything driving a texture off curvature needs `--smooth`.
"""
import argparse
import math


def torus(nu, nv, major=0.32, minor=0.13):
    """Torus of revolution about +Y. Returns (verts, normals, faces).

    The outward unit normal is exact and analytic: at parameter (u, v) the point sits
    minor*(cos v) out along the tube's radial direction and minor*(sin v) up, so the
    normal is just that offset direction normalised — which is already unit, since
    (cos v, sin v) is. Principal curvatures are 1/minor around the tube and
    cos v / (major + minor cos v) around the ring, so mean curvature runs from
    strongly POSITIVE on the outer equator (v=0) to NEGATIVE on the inner throat
    (v=pi) — which is what makes a torus the natural test shape for `curv`.
    """
    verts, norms, faces = [], [], []
    for i in range(nu):
        u = 2 * math.pi * i / nu
        for j in range(nv):
            v = 2 * math.pi * j / nv
            cu, su, cv, sv = math.cos(u), math.sin(u), math.cos(v), math.sin(v)
            x = (major + minor * cv) * cu
            y = minor * sv
            z = (major + minor * cv) * su
            verts.append((x, y, z))
            norms.append((cv * cu, sv, cv * su))
    for i in range(nu):
        for j in range(nv):
            a = i * nv + j
            b = ((i + 1) % nu) * nv + j
            c = ((i + 1) % nu) * nv + (j + 1) % nv
            d = i * nv + (j + 1) % nv
            faces.append((a, b, c))
            faces.append((a, c, d))
    return verts, norms, faces


def icosphere(subdiv, radius=0.28):
    t = (1 + math.sqrt(5)) / 2
    verts = [(-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0),
             (0, -1, t), (0, 1, t), (0, -1, -t), (0, 1, -t),
             (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1)]
    faces = [(0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
             (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
             (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
             (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1)]
    verts = [list(v) for v in verts]
    cache = {}

    def midpoint(a, b):
        key = (min(a, b), max(a, b))
        if key in cache:
            return cache[key]
        m = [(verts[a][k] + verts[b][k]) / 2 for k in range(3)]
        verts.append(m)
        cache[key] = len(verts) - 1
        return cache[key]

    for _ in range(subdiv):
        newf = []
        for a, b, c in faces:
            ab, bc, ca = midpoint(a, b), midpoint(b, c), midpoint(c, a)
            newf += [(a, ab, ca), (b, bc, ab), (c, ca, bc), (ab, bc, ca)]
        faces = newf

    # The subdivided icosahedron is projected onto the sphere, so the outward normal at
    # a vertex is exactly its own normalised position — and mean curvature is a uniform
    # 1/radius everywhere, which makes the sphere the constant-curvature control next to
    # the torus's varying one.
    out, norms = [], []
    for v in verts:
        n = math.sqrt(sum(k * k for k in v)) or 1.0
        out.append(tuple(radius * k / n for k in v))
        norms.append(tuple(k / n for k in v))
    return out, norms, faces


def write_obj(path, verts, norms, faces, smooth=False):
    with open(path, "w") as f:
        f.write(f"# generated by make_mesh.py: {len(verts)} verts, {len(faces)} tris"
                f"{', analytic vn' if smooth else ''}\n")
        for x, y, z in verts:
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        if smooth:
            for x, y, z in norms:
                f.write(f"vn {x:.6f} {y:.6f} {z:.6f}\n")
        for a, b, c in faces:
            if smooth:
                # `v//vn` — positions and normals share one index space here, since every
                # vertex carries exactly one analytic normal.
                f.write(f"f {a + 1}//{a + 1} {b + 1}//{b + 1} {c + 1}//{c + 1}\n")
            else:
                f.write(f"f {a + 1} {b + 1} {c + 1}\n")
    print(f"wrote {path}: {len(verts)} verts, {len(faces)} tris"
          f"{', smooth (vn)' if smooth else ', flat'}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("shape", choices=["torus", "sphere"])
    ap.add_argument("-o", "--out", default="mesh.obj")
    ap.add_argument("--nu", type=int, default=128)
    ap.add_argument("--nv", type=int, default=64)
    ap.add_argument("--subdiv", type=int, default=4)
    # Torus radii. The defaults are the historical ones, kept so the checked-in scenes
    # that use torus.obj regenerate identically. Note 2*minor < major there, which makes
    # the tube's 1/minor curvature dominate and leaves MEAN curvature positive even in
    # the throat; a torus that actually goes concave (H < 0) needs 2*minor > major, e.g.
    # `--major 0.32 --minor 0.2`.
    ap.add_argument("--major", type=float, default=0.32, help="torus ring radius")
    ap.add_argument("--minor", type=float, default=0.13, help="torus tube radius")
    ap.add_argument("--radius", type=float, default=0.28, help="sphere radius")
    ap.add_argument("--smooth", action="store_true",
                    help="emit analytic per-vertex normals (vn) for smooth shading; "
                         "required for the `curv` pattern variable to read nonzero")
    a = ap.parse_args()
    if a.shape == "torus":
        v, n, f = torus(a.nu, a.nv, a.major, a.minor)
    else:
        v, n, f = icosphere(a.subdiv, a.radius)
    write_obj(a.out, v, n, f, a.smooth)


if __name__ == "__main__":
    main()
