#!/usr/bin/env python3
"""Generate simple parametric test meshes as Wavefront OBJ.

Used to stress the renderer's BVH and mesh loader with thousands of triangles.
The geometry is emitted in a unit-ish scale centred at the origin; place it in a
scene with the loader's translate/scale.

Examples:
    python make_mesh.py torus  -o torus.obj  --nu 128 --nv 64
    python make_mesh.py sphere -o sphere.obj --subdiv 5
"""
import argparse
import math


def torus(nu, nv, major=0.32, minor=0.13):
    verts, faces = [], []
    for i in range(nu):
        u = 2 * math.pi * i / nu
        for j in range(nv):
            v = 2 * math.pi * j / nv
            cu, su, cv, sv = math.cos(u), math.sin(u), math.cos(v), math.sin(v)
            x = (major + minor * cv) * cu
            y = minor * sv
            z = (major + minor * cv) * su
            verts.append((x, y, z))
    for i in range(nu):
        for j in range(nv):
            a = i * nv + j
            b = ((i + 1) % nu) * nv + j
            c = ((i + 1) % nu) * nv + (j + 1) % nv
            d = i * nv + (j + 1) % nv
            faces.append((a, b, c))
            faces.append((a, c, d))
    return verts, faces


def icosphere(subdiv, radius=0.28):
    t = (1 + math.sqrt(5)) / 2
    verts = [(-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0),
             (0, -1, t), (0, 1, t), (0, -1, -t), (0, 1, -t),
             (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1)]
    faces = [(0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
             (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
             (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
             (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1)]
    verts = [list(v) for v in verts]
    cache = {}

    def midpoint(a, b):
        key = (min(a, b), max(a, b))
        if key in cache:
            return cache[key]
        m = [(verts[a][k] + verts[b][k]) / 2 for k in range(3)]
        verts.append(m)
        cache[key] = len(verts) - 1
        return cache[key]

    for _ in range(subdiv):
        newf = []
        for a, b, c in faces:
            ab, bc, ca = midpoint(a, b), midpoint(b, c), midpoint(c, a)
            newf += [(a, ab, ca), (b, bc, ab), (c, ca, bc), (ab, bc, ca)]
        faces = newf

    out = []
    for v in verts:
        n = math.sqrt(sum(k * k for k in v)) or 1.0
        out.append(tuple(radius * k / n for k in v))
    return out, faces


def write_obj(path, verts, faces):
    with open(path, "w") as f:
        f.write(f"# generated by make_mesh.py: {len(verts)} verts, {len(faces)} tris\n")
        for x, y, z in verts:
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for a, b, c in faces:
            f.write(f"f {a + 1} {b + 1} {c + 1}\n")
    print(f"wrote {path}: {len(verts)} verts, {len(faces)} tris")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("shape", choices=["torus", "sphere"])
    ap.add_argument("-o", "--out", default="mesh.obj")
    ap.add_argument("--nu", type=int, default=128)
    ap.add_argument("--nv", type=int, default=64)
    ap.add_argument("--subdiv", type=int, default=4)
    a = ap.parse_args()
    if a.shape == "torus":
        v, f = torus(a.nu, a.nv)
    else:
        v, f = icosphere(a.subdiv)
    write_obj(a.out, v, f)


if __name__ == "__main__":
    main()
