#!/usr/bin/env python3
"""Generate src/pov_noise.h - an EXACT host+device port of POV-Ray's Perlin
noise (the `Noise()` scalar used by the internal isosurface functions
f_noise3d, f_noise_generator, f_ridge, f_ridged_mf, f_hetero_mf).

POV's noise is table-driven: three tables are built once at startup by a
deterministic pseudo-random procedure (a 32-bit LCG, seed 0 or 1), plus a
fixed literal gradient table `RTable`.  To reproduce POV bit-for-bit we
replicate those init procedures here (in Python) and bake the resulting
tables into the header as constant data, so the same numbers exist on the
CPU and GPU with no runtime init.

Three noise generators are supported, matching POV exactly:
  1 = kNoiseGen_Original       (RTable/hashTable path, range +0.5)
  2 = kNoiseGen_RangeCorrected (RTable/hashTable path, range-corrected) - default
  3 = kNoiseGen_Perlin         (SolidNoise: gradient lattice)

Reproducible: POV-Ray source is fetched from GitHub (pinned raw URLs) and
cached next to this script.  Run `python tools/pov_noise_gen.py`.
"""
import re, os, urllib.request

BASE = "https://raw.githubusercontent.com/POV-Ray/povray/master/source/core/material/"
FILES = {"noise": BASE + "noise.cpp", "portable": BASE + "portablenoise.cpp"}
HERE = os.path.dirname(__file__)
OUT = os.path.join(HERE, "..", "src", "pov_noise.h")


def fetch(key):
    cache = os.path.join(HERE, ".pov_" + key + ".cpp")
    if not os.path.exists(cache):
        print(f"fetching {FILES[key]}")
        urllib.request.urlretrieve(FILES[key], cache)
    return open(cache, "r", encoding="utf-8", errors="replace").read()


noise_src = fetch("noise")

# --- parse the literal RTable (267 seed values in the even slots) --------------
m = re.search(r"RTable\[267\*2\]\s*=\s*\{(.*?)\}", noise_src, re.S)
nums = re.findall(r"-?\d+\.?\d*(?:e[-+]?\d+)?", m.group(1))
vals = [float(x) for x in nums]
# The source lists (v, 0.0) pairs; keep only the real value slots (every other).
seed_vals = vals[0::2]
assert len(seed_vals) == 267, len(seed_vals)
# RTable[2i]=v, RTable[2i+1]=v*0.5  (POV fills the .5 copies in Initialize_Noise)
RTABLE = []
for v in seed_vals:
    RTABLE.append(v)
    RTABLE.append(v * 0.5)
assert len(RTABLE) == 534

# --- replicate InitTextureTable() -> hashTable[8192] --------------------------
# next_rand starts 0; 32-bit LCG; only bits 16..30 are used (>>16 & 0x7FFF) so
# signedness is irrelevant and unsigned 32-bit arithmetic reproduces it exactly.
def lcg(r):
    return (r * 1812433253 + 12345) & 0xFFFFFFFF


hashTable = list(range(4096))
nr = 0
for i in range(4095, -1, -1):
    nr = lcg(nr)
    j = ((nr >> 16) & 0x7FFF) % 4096
    hashTable[i], hashTable[j] = hashTable[j], hashTable[i]
hashTable = hashTable + hashTable[:]  # duplicate to 8192
assert len(hashTable) == 8192

# --- replicate InitSolidNoise() -> NoisePermutation + NoiseGradients ----------
NE = 2048
grads = [(0.0, 0.0, 0.0)] * (2 * (NE + 1))
perm = [0] * (2 * (NE + 1))
nr = 1
import math
for i in range(NE):
    while True:
        v = [0.0, 0.0, 0.0]
        for j in range(3):
            nr = lcg(nr)
            v[j] = float((((nr >> 16) & 0x7FFF) % (NE << 1)) - NE) / float(NE)
        s = v[0] * v[0] + v[1] * v[1] + v[2] * v[2]
        if not (s > 1.0 or s < 1.0e-5):
            break
    inv = 1.0 / math.sqrt(s)
    grads[i] = (v[0] * inv, v[1] * inv, v[2] * inv)
for i in range(NE):
    perm[i] = i
i = NE
while i > 0:
    k = perm[i]
    nr = lcg(nr)
    j = ((nr >> 16) & 0x7FFF) % NE
    perm[i] = perm[j]
    perm[j] = k
    i -= 2
for i in range(NE + 2):
    perm[NE + i] = perm[i]
    grads[NE + i] = grads[i]


def fmt(x):
    # emit full double precision, round-trippable
    return repr(float(x))


def col(items, per=12, fmt_fn=str, indent="    "):
    out = []
    for k in range(0, len(items), per):
        out.append(indent + ", ".join(fmt_fn(v) for v in items[k:k + per]) + ",")
    return "\n".join(out)


hash_txt = col(hashTable, 16, str)
rt_txt = col(RTABLE, 6, fmt)
perm_txt = col(perm, 16, str)
grad_flat = []
for g in grads:
    grad_flat.extend(g)
grad_txt = col(grad_flat, 6, fmt)

TEMPLATE = r'''// pov_noise.h - EXACT host+device port of POV-Ray's Perlin noise Noise().
//
// AUTO-GENERATED by tools/pov_noise_gen.py.  Do not edit by hand; re-run it.
//
// POV builds three lookup tables at startup with a deterministic 32-bit LCG
// (see tools/pov_noise_gen.py).  We bake the results in as constant data so
// the CPU and GPU evaluate identical noise with no runtime initialization.
//
//   povNoise(x,y,z, gen)  ==  POV's  Noise(Vector3d(x,y,z), gen)
//     gen 1 = kNoiseGen_Original,  2 = kNoiseGen_RangeCorrected (default),
//     gen 3 = kNoiseGen_Perlin.
//
// Storage: under nvcc device passes the tables live in ordinary device GLOBAL
// memory (__device__), so they are not subject to the 64 KB constant-memory
// limit.  On the host (and nvcc host pass) they are plain static const.  The
// single povNoise() body reads whichever is in scope for the current pass.
#pragma once

#if defined(__CUDACC__)
  #ifndef POV_HD
  #define POV_HD __host__ __device__
  #endif
#else
  #ifndef POV_HD
  #define POV_HD
  #endif
#endif

#include <math.h>

#ifdef __CUDA_ARCH__
  #define POVN_MEM __device__ const
#else
  #define POVN_MEM static const
#endif

// ---- baked tables -----------------------------------------------------------
POVN_MEM unsigned short g_povHash[8192] = {
{hash}
};

POVN_MEM double g_povRTable[534] = {
{rtable}
};

// Perlin (gen 3) gradient lattice: NoisePermutation[2*(2048+1)] and
// NoiseGradients[2*(2048+1)][3], flattened.
POVN_MEM int g_povPerm[4098] = {
{perm}
};
POVN_MEM double g_povGrad[12294] = {
{grad}
};

// ---- SolidNoise (Perlin, gen 3) ---------------------------------------------
POV_HD inline double povSCurve(double t) { return t * t * (3.0 - 2.0 * t); }
POV_HD inline double povLerp(double t, double a, double b) { return a + t * (b - a); }

POV_HD inline double povSolidNoise(double px, double py, double pz) {
    const int NE = 2048;
    const double ROLLOVER = 10000000.023157213;
    double P[3] = { px, py, pz };
    int b0[3], b1[3];
    double r0[3], r1[3];
    for (int i = 0; i < 3; ++i) {
        double t = P[i] + ROLLOVER;
        int it = (int)floor(t);
        b0[i] = it & (NE - 1);
        b1[i] = (b0[i] + 1) & (NE - 1);
        r0[i] = t - it;
        r1[i] = r0[i] - 1.0;
    }
    int ii = g_povPerm[b0[0]];
    int jj = g_povPerm[b1[0]];
    int b00 = g_povPerm[ii + b0[1]];
    int b10 = g_povPerm[jj + b0[1]];
    int b01 = g_povPerm[ii + b1[1]];
    int b11 = g_povPerm[jj + b1[1]];
    double sx = povSCurve(r0[0]), sy = povSCurve(r0[1]), sz = povSCurve(r0[2]);
#define POVG(idx,gx,gy,gz) (g_povGrad[((idx))*3+0]*(gx)+g_povGrad[((idx))*3+1]*(gy)+g_povGrad[((idx))*3+2]*(gz))
    double u, v, a, b, c, d;
    u = POVG(b00 + b0[2], r0[0], r0[1], r0[2]);
    v = POVG(b10 + b0[2], r1[0], r0[1], r0[2]);
    a = povLerp(sx, u, v);
    u = POVG(b01 + b0[2], r0[0], r1[1], r0[2]);
    v = POVG(b11 + b0[2], r1[0], r1[1], r0[2]);
    b = povLerp(sx, u, v);
    c = povLerp(sy, a, b);
    u = POVG(b00 + b1[2], r0[0], r0[1], r1[2]);
    v = POVG(b10 + b1[2], r1[0], r0[1], r1[2]);
    a = povLerp(sx, u, v);
    u = POVG(b01 + b1[2], r0[0], r1[1], r1[2]);
    v = POVG(b11 + b1[2], r1[0], r1[1], r1[2]);
    b = povLerp(sx, u, v);
    d = povLerp(sy, a, b);
#undef POVG
    return povLerp(sz, c, d);
}

// ---- PortableNoise (gens 1 & 2) + generator dispatch ------------------------
// povNoise: POV's Noise(EPoint, noise_generator).  Returns a value in ~[0,1].
POV_HD inline double povNoise(double x, double y, double z, int gen) {
    const double POV_EPS = 1.0e-10;
    if (gen == 3) { // kNoiseGen_Perlin
        double sum = 0.5 * (1.59 * povSolidNoise(x, y, z) + 0.985);
        if (sum < 0.0) sum = 0.0;
        if (sum > 1.0) sum = 1.0;
        return sum;
    }
    int tmp;
    tmp = (x >= 0) ? (int)x : (int)(x - (1 - POV_EPS));
    int ix = (int)((tmp - (-10000)) & 0xFFF);
    double x_ix = x - tmp;
    tmp = (y >= 0) ? (int)y : (int)(y - (1 - POV_EPS));
    int iy = (int)((tmp - (-10000)) & 0xFFF);
    double y_iy = y - tmp;
    tmp = (z >= 0) ? (int)z : (int)(z - (1 - POV_EPS));
    int iz = (int)((tmp - (-10000)) & 0xFFF);
    double z_iz = z - tmp;
    double x_jx = x_ix - 1, y_jy = y_iy - 1, z_jz = z_iz - 1;
    double sx = povSCurve(x_ix), sy = povSCurve(y_iy), sz = povSCurve(z_iz);
    double tx = 1 - sx, ty = 1 - sy, tz = 1 - sz;
    double txty = tx * ty, sxty = sx * ty, txsy = tx * sy, sxsy = sx * sy;
#define POVH2(a,b) (g_povHash[(int)(g_povHash[(int)(a)] ^ (b))])
#define POVH1I(a,b) ((g_povHash[(int)(a) ^ (b)] & 0xFF) * 2)
    int ixiy = POVH2(ix,     iy);
    int jxiy = POVH2(ix + 1, iy);
    int ixjy = POVH2(ix,     iy + 1);
    int jxjy = POVH2(ix + 1, iy + 1);
#define POVINCR(mp,s,px,py,pz) ((s)*((mp)[1] + (mp)[2]*(px) + (mp)[4]*(py) + (mp)[6]*(pz)))
    const double* mp;
    double sum = 0.0;
    mp = &g_povRTable[POVH1I(ixiy, iz)];     sum  = POVINCR(mp, (txty*tz), x_ix, y_iy, z_iz);
    mp = &g_povRTable[POVH1I(jxiy, iz)];     sum += POVINCR(mp, (sxty*tz), x_jx, y_iy, z_iz);
    mp = &g_povRTable[POVH1I(ixjy, iz)];     sum += POVINCR(mp, (txsy*tz), x_ix, y_jy, z_iz);
    mp = &g_povRTable[POVH1I(jxjy, iz)];     sum += POVINCR(mp, (sxsy*tz), x_jx, y_jy, z_iz);
    mp = &g_povRTable[POVH1I(ixiy, iz + 1)]; sum += POVINCR(mp, (txty*sz), x_ix, y_iy, z_jz);
    mp = &g_povRTable[POVH1I(jxiy, iz + 1)]; sum += POVINCR(mp, (sxty*sz), x_jx, y_iy, z_jz);
    mp = &g_povRTable[POVH1I(ixjy, iz + 1)]; sum += POVINCR(mp, (txsy*sz), x_ix, y_jy, z_jz);
    mp = &g_povRTable[POVH1I(jxjy, iz + 1)]; sum += POVINCR(mp, (sxsy*sz), x_jx, y_jy, z_jz);
#undef POVH2
#undef POVH1I
#undef POVINCR
    if (gen == 2) { // kNoiseGen_RangeCorrected (default)
        sum += 1.05242;
        sum *= 0.48985582;
    } else {        // kNoiseGen_Original (and gen 0 default fall-through)
        sum += 0.5;
    }
    if (sum < 0.0) sum = 0.0;
    if (sum > 1.0) sum = 1.0;
    return sum;
}

#undef POVN_MEM
'''

hdr = (TEMPLATE
       .replace("{hash}", hash_txt)
       .replace("{rtable}", rt_txt)
       .replace("{perm}", perm_txt)
       .replace("{grad}", grad_txt))

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write(hdr)
print(f"wrote {OUT}")
print(f"  hashTable[8192], RTable[534], perm[4098], grad[12294]")
