// pov_functions.h - EXACT ports of POV-Ray's internal isosurface functions.
//
// AUTO-GENERATED by tools/pov_functions_gen.py from POV-Ray source
// (source/vm/fnintern.cpp).  Do not edit by hand; re-run the generator.
//
// Each function is POV internal(N).  In SDL you call them as
//   f_name(x, y, z, P0, P1, ...)
// i.e. the first three args are the coordinates and the rest are parameters.
// Here povFnEval(id, p) takes p[0..2]=x,y,z and p[3..]=P0.. and returns the
// same DBL the POV function returns, using the identical algebra.
//
// The same evaluator runs on the CPU (pattern.h / patternEval) and the GPU
// (render_cuda.cu / dPatternEval), so results agree bit-for-bit across backends.
//
// EXCLUDED (need POV's Perlin-noise / pattern / pigment / spline engine, not yet
// ported): f_pattern(77).
#pragma once

#if defined(__CUDACC__)
  #ifndef POV_HD
  #define POV_HD __host__ __device__
  #endif
#else
  #ifndef POV_HD
  #define POV_HD
  #endif
#endif

#include <math.h>
// povNoise() - exact host+device port of POV's Perlin Noise(), used by the
// noise-based internal functions (f_noise3d, f_noise_generator, f_ridge,
// f_ridged_mf, f_hetero_mf).
#include "pov_noise.h"

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
#ifndef M_PI_180
#define M_PI_180 (M_PI / 180.0)
#endif
#ifndef TWO_M_PI
#define TWO_M_PI (2.0 * M_PI)
#endif

// POV's ROT2D "surface of revolution" switch, verbatim (operates on the mutable
// PARAM_X/PARAM_Y locals and recomputes x2,y2).  p>0 enables the revolve.
#define ROT2D(p,d,ang) if (p>0) {x2=sqrt(x2+PARAM_Z*PARAM_Z)- d; th=(ang)*M_PI_180; \
    if (th!=0){ PARAM_X= x2*cos(th)-PARAM_Y*sin(th); PARAM_Y= x2*sin(th)+PARAM_Y*cos(th);} else PARAM_X=x2; \
    x2=PARAM_X*PARAM_X; y2=PARAM_Y*PARAM_Y;}

// The largest arity (f_helical_torus) is 13 (3 coords + 10 params).
#define POV_FN_MAX_ARGS 13

// Evaluate POV internal function `id` with args _pp[] (_pp[0..2]=x,y,z,
// _pp[3..]=P0..).  The param is named `_pp` (not `p`) to avoid colliding with POV
// bodies that declare a local `p` (e.g. f_superellipsoid).
POV_HD inline double povFnEval(int id, const double* _pp) {
    double X = _pp[0], Y = _pp[1], Z = _pp[2];
#define PARAM_X X
#define PARAM_Y Y
#define PARAM_Z Z
#define PARAM(i) (_pp[(i) + 3])
    switch (id) {
    case 0: { // f_algbr_cyl1
    double r, x2, y2, th;

    x2 = PARAM_X * PARAM_X;
    y2 = PARAM_Y * PARAM_Y;

    ROT2D(PARAM(2),PARAM(3),PARAM(4))

    PARAM_X = fabs(PARAM_X);

    r = -(x2 * PARAM_X - x2 + y2);

    return (-fmin(PARAM(1), fmax(PARAM(0) * r, -PARAM(1))));
    }
    case 1: { // f_algbr_cyl2
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, th;
    ROT2D(PARAM(2),PARAM(3),PARAM(4))
    r=-( 2*x2*x2 -3*x2*PARAM_Y +y2 -2*y2*PARAM_Y +y2*y2 );
    return( fmin(PARAM(1), fmax(PARAM(0)*r,-PARAM(1))) );
    }
    case 2: { // f_algbr_cyl3
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, th;
    ROT2D(PARAM(2),PARAM(3),PARAM(4))
    r=-( x2*x2 +x2*y2 -2*x2*PARAM_Y -PARAM_X*y2 +y2 );
    return( fmin(PARAM(1), fmax(PARAM(0)*r,-PARAM(1))) );
    }
    case 3: { // f_algbr_cyl4
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, th;
    ROT2D(PARAM(2),PARAM(3),PARAM(4))
    r=-( x2*x2 +y2*y2 +2*x2*y2 +3*x2*PARAM_Y -y2*PARAM_Y );
    return( fmin(PARAM(1), fmax(PARAM(0)*r,-PARAM(1))) );
    }
    case 4: { // f_bicorn
    double r, r2,x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r = PARAM(1)*PARAM(1);
    r2=(x2 + z2 + 2*PARAM(1)*PARAM_Y - r);
    r = ( y2*(r - (x2 + z2)) - r2*r2);
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 5: { // f_bifolia
    double r, x2=PARAM_X*PARAM_X, z2=PARAM_Z*PARAM_Z;
    r=x2+PARAM_Y*PARAM_Y+z2;
    r= -(r*r - PARAM(1)*(x2 + z2)*PARAM_Y);
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 6: { // f_blob
    double r,r2,y2,z2,temp;
    /*   blob  */
    y2=PARAM_Y*PARAM_Y; z2=PARAM_Z*PARAM_Z;
    r2= PARAM(0)*0.5;
    r=((PARAM_X+r2)*(PARAM_X+r2)+y2+z2)*PARAM(2)*PARAM(2);
    if (r>1.)
        r=1.;
    temp=( (PARAM_X - r2)*(PARAM_X - r2)+y2+z2)*PARAM(4)*PARAM(4);
    if (temp>1)
        temp=1.;
    return(-(PARAM(1) *(1.-r) *(1.-r)  +PARAM(3) *(1.-temp)*(1.-temp) ));
    }
    case 7: { // f_blob2
    double r,x2,y2,z2;
    x2=PARAM_X*PARAM_X; y2=PARAM_Y*PARAM_Y; z2=PARAM_Z*PARAM_Z;
    /*  f= f1 + f2 */
    r=exp(-(x2+y2+z2)*PARAM(1)) + exp(-((PARAM_X-PARAM(0))*(PARAM_X-PARAM(0))+y2+z2)*PARAM(1));
    return(PARAM(3)-r*PARAM(2));
    }
    case 8: { // f_boy_surface
    double r, r2,ph,x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r2=1-PARAM_Z; ph=x2+y2;
    r= PARAM(1)*(64*r2*r2*r2*z2*PARAM_Z- 48*r2*r2*z2*(3*x2+3*y2+2*z2)+
    12*r2*PARAM_Z*(27*ph*ph-24*z2*ph+ 36*sqrt(2.0)*PARAM_Y*PARAM_Z*(y2-3*x2)+4*z2*z2)+
    (9*x2+9*y2-2*z2)*(-81*ph*ph-72*z2*ph+
    108*sqrt(2.0)*PARAM_X*PARAM_Z*(x2-3*y2)+4*z2*z2) );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 9: { // f_comma
    double r,th,temp;
    if ((PARAM_X==0)&&(PARAM_Z==0))
        PARAM_X=0.0001;
    th=atan2(PARAM_Z,PARAM_X);
    r=sqrt( (PARAM_X + PARAM(0)*0.25)*(PARAM_X + PARAM(0)*0.25) + PARAM_Z*PARAM_Z);
    temp= cos(th*0.5) * PARAM(0)*0.5 -sqrt((r- PARAM(0)*0.75)*(r - PARAM(0)*0.75)+PARAM_Y*PARAM_Y);
    temp= fmin(PARAM_Z, temp);
    r= PARAM(0)*0.5   - sqrt( (PARAM_X - PARAM(0)*0.5)*(PARAM_X - PARAM(0)*0.5) + PARAM_Z*PARAM_Z + PARAM_Y*PARAM_Y);
    return(-(double)fmax(temp,r));
    }
    case 10: { // f_cross_ellipsoids
    double r,x2,y2,z2;
    x2=PARAM_X*PARAM_X; y2=PARAM_Y*PARAM_Y; z2=PARAM_Z*PARAM_Z;
    /*  f= max (f1, f2, f3) */
    r=fmax(exp(-(x2*PARAM(0)+y2*PARAM(0)+z2)*PARAM(1)), exp(-(x2*PARAM(0)+y2+z2*PARAM(0))*PARAM(1)));
    r=fmax(r, exp(-(x2+y2*PARAM(0)+z2*PARAM(0))*PARAM(1)));
    return(PARAM(3)-r*PARAM(2));
    }
    case 11: { // f_crossed_trough
    double r;
    r=( PARAM_X*PARAM_X * PARAM_Z*PARAM_Z - PARAM_Y  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 12: { // f_cubic_saddle
    double r;
    r=-(PARAM_X*PARAM_X*PARAM_X - PARAM_Y*PARAM_Y*PARAM_Y - PARAM_Z);
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 13: { // f_cushion
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r= (z2*x2 - z2*z2 - 2*PARAM_Z*x2 + 2*z2*PARAM_Z + x2 - z2
    -(x2 - PARAM_Z)*(x2 - PARAM_Z) - y2*y2 - 2*x2*y2 - y2*z2 + 2*y2*PARAM_Z + y2);
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 14: { // f_devils_curve
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=-(x2*x2 + 2*x2*z2 - 0.36*x2 - y2*y2 + 0.25*y2 + z2*z2);
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 15: { // f_devils_curve_2d
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, th;
    ROT2D(PARAM(3),PARAM(4),PARAM(5))
    r=-( x2 * (x2 - PARAM(1)*PARAM(1)) -  y2 * (y2 - PARAM(2)*PARAM(2)) );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 16: { // f_dupin_cyclid
    double r, r2,x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z, ph,th, p1,p2,p3,p4;
    r2=PARAM(5)*PARAM(5);
    ph=PARAM(2)*PARAM(2); th=PARAM(4)*PARAM(4);
    p1= ph - th - (PARAM(3) + PARAM(1))*(PARAM(3) + PARAM(1));
    p2= ph - th - (PARAM(3) - PARAM(1))*(PARAM(3) - PARAM(1));
    p3= PARAM(3)*PARAM(3); p4=PARAM(1)*PARAM(1);
    r=-( p1*p2* (x2*x2+y2*y2+z2*z2)+ 2*(p1*p2* (x2*y2+x2*z2+y2*z2))+
    2*r2*((-th-p3 + ph+p4)* (2*PARAM_X*PARAM(3)+2*PARAM_Y*PARAM(4)-r2)-4*PARAM(4)*ph*PARAM_Y)*
    (x2+y2+z2)+ 4*r2*r2*(PARAM(3)*PARAM_X+PARAM(4)*PARAM_Y)
    *(-r2+PARAM(4)*PARAM_Y+PARAM(3)*PARAM_X)+ 4*r2*r2*p4*y2+ r2*r2*r2*r2);
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 17: { // f_ellipsoid
    /*   sphere  */
    return(sqrt(PARAM_X*PARAM_X * PARAM(0)*PARAM(0) + PARAM_Y*PARAM_Y * PARAM(1)*PARAM(1) + PARAM_Z*PARAM_Z * PARAM(2)*PARAM(2)));
    }
    case 18: { // f_enneper
    double r, r2,x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    if (fabs(PARAM_Z)<0.2)
        PARAM_Z=0.2;
    r =((y2-x2)/(2*PARAM_Z)+2*z2/9+(2/3.));
    r2=((y2-x2)/(4*PARAM_Z)-(1/4.)*(x2+y2+(8/9.)*z2)+(2/9.));
    r=-( r*r*r -6*r2*r2);
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 19: { // f_flange_cover
    double r,x2,y2,z2;
    x2=PARAM_X*PARAM_X; y2=PARAM_Y*PARAM_Y; z2=PARAM_Z*PARAM_Z;
    /*  f= f1 + f2 + f3 */
    r=exp(-(x2*PARAM(0)+y2*PARAM(0)+z2)*PARAM(1)) + exp(-(x2*PARAM(0)+y2+z2*PARAM(0))*PARAM(1)) +
    exp(-(x2+y2*PARAM(0)+z2*PARAM(0))*PARAM(1));
    return(PARAM(3)-r*PARAM(2));
    }
    case 20: { // f_folium_surface
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=((y2 + z2) * (1+(PARAM(2) - 4*PARAM(1))*PARAM_X)+x2*(1 + PARAM(2)));
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 21: { // f_folium_surface_2d
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z, th;
    ROT2D(PARAM(3),PARAM(4),PARAM(5))
    r = -( y2  * (1 + (PARAM(2) - 4*PARAM(1))*PARAM_X) + x2*(1 + PARAM(2)));
    return( fmin(10., fmax(PARAM(0)*r, -10.)) );
    }
    case 22: { // f_glob
    double r, x2=PARAM_X*PARAM_X;
    r= ( 0.5*x2*x2*PARAM_X + 0.5*x2*x2 - (PARAM_Y*PARAM_Y + PARAM_Z*PARAM_Z)  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 23: { // f_heart
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=-( (2*x2+y2+z2-1)*(2*x2+y2+z2-1)*(2*x2+y2+z2-1)-
    0.1*x2*z2*PARAM_Z-y2*z2*PARAM_Z  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 24: { // f_helical_torus
    double r,r2, temp,th,ph;
    r2=sqrt(PARAM_X*PARAM_X+PARAM_Z*PARAM_Z);
    if ((PARAM_X==0)&&(PARAM_Z==0))
        PARAM_X=0.000001;
    ph=atan2(PARAM_X,PARAM_Z);
    temp=atan2(r2 - PARAM(0), PARAM_Y);
    r=sqrt((r2-PARAM(0))*(r2-PARAM(0))+PARAM_Y*PARAM_Y);
    th=fmod(ph*PARAM(1)+temp*PARAM(2), TWO_M_PI);
    if (th<0)
        th+=TWO_M_PI;
    temp=atan2((th-M_PI)*PARAM(8), r-PARAM(5));
    temp=cos(temp*PARAM(7)+ph*PARAM(9))*PARAM(3)+PARAM(4);
    r2=PARAM(4)+PARAM(5)-PARAM(0)-r2;
    th=th - M_PI;
    temp=temp-fmin(sqrt((r-PARAM(5))*(r-PARAM(5))+th*th*PARAM(6)), (r+PARAM(5)));
    return(-fmax(r2,temp));
    }
    case 25: { // f_helix1
    double r, r2, temp, th, ph, x2;
    /* helix                                     *
     *   p[0] : number of helix                  *
     *   p[1] : frequency                        *
     *   p[2] : minor radius                     *
     *   p[3] : major radius                     *
     *   p[4] : shape parameter                  *
     *   p[5] : cross section                    *
     *             p[5] = 1:  circle             *
     *                  = 2:  diamond            *
     *                  < 1:  rectangle(rounded) *
     *   p[6] : rotation angle for p[5]<1        */

    r = sqrt(PARAM_X * PARAM_X + PARAM_Z * PARAM_Z);
    if ((PARAM_X == 0) && (PARAM_Z == 0))
        PARAM_X = 0.000001;
    th = atan2(PARAM_Z, PARAM_X);
    th = fmod(th * PARAM(0) + PARAM_Y * PARAM(1) * PARAM(0), TWO_M_PI);
    if (th < 0)
        th += TWO_M_PI;
    PARAM_Z = (th - M_PI) / PARAM(4) / (PARAM(1) * PARAM(0));

    PARAM_X = r - PARAM(3);
    if (PARAM(5) == 1)
        r2 = sqrt(PARAM_X * PARAM_X + PARAM_Z * PARAM_Z);
    else
    {
        if (PARAM(6) != 0)
        {
            th = cos(PARAM(6) * M_PI_180);
            ph = sin(PARAM(6) * M_PI_180);
            x2 = PARAM_X * th - PARAM_Z * ph;
            PARAM_Z = PARAM_X * ph + PARAM_Z * th;
            PARAM_X = x2;
        }
        if (PARAM(5) != 0)
        {
            temp = 2. / PARAM(5);
            r2 = pow((pow(fabs(PARAM_X), temp) + pow(fabs(PARAM_Z), temp)), PARAM(5) *.5);
        }
        else
            r2 = fmax(fabs(PARAM_X), fabs(PARAM_Z));
    }

    return (-PARAM(2) + fmin((PARAM(3) + r), r2));
    }
    case 26: { // f_helix2
    double th, ph, x2, z2, r2, temp;
    /* helical shape  for (minor radius>major radius  *
     *    cross section   p[5] same as NFUNCTION = 6      */
    th = PARAM_Y * PARAM(1);
    ph = cos(th);
    th = sin(th);
    x2 = PARAM_X - PARAM(3) * ph;
    z2 = PARAM_Z - PARAM(3) * th;
    PARAM_X = x2 * ph + z2 * th;
    PARAM_Z = (-x2 * th + z2 * ph);

    if (PARAM(5) == 1)
        return (sqrt(PARAM_X * PARAM_X + PARAM_Z * PARAM_Z) - PARAM(2));
    if (PARAM(5) != 0)
    {
        temp = 2. / PARAM(5);
        r2 = pow((pow(fabs(PARAM_X), temp) + pow(fabs(PARAM_Z), temp)), PARAM(5) *.5);
    }
    else
        r2 = fmax(fabs(PARAM_X), fabs(PARAM_Z));

    return (r2 - PARAM(2));
    }
    case 27: { // f_hex_x
    double x1,y1,x2,y2, th;
    x1=fabs(fmod(fabs(PARAM_X), sqrt(3.0))-sqrt(3.0)/2);
    y1=fabs(fmod(fabs(PARAM_Y), 3)-1.5);
    x2=sqrt(3.0)/2-x1;
    y2=1.5-y1;
    if ((x1*x1+y1*y1)>(x2*x2+y2*y2))
    {
        x1=x2;
        y1=y2;
    }
    if ((x1==0)&&(y1==0))
        PARAM_X=0.000001;
    th=atan2(y1,x1);
    if (th<M_PI/6)
        return(x1);
    else
    {
        x1=cos(M_PI/3)*x1+sin(M_PI/3)*y1;
        return(x1);
    }
    }
    case 28: { // f_hex_y
    double x1,y1,x2,y2, th;
    x1=fabs(fmod(fabs(PARAM_X), sqrt(3.0))-sqrt(3.0)/2);
    y1=fabs(fmod(fabs(PARAM_Y), 3)-1.5);
    x2=sqrt(3.0)/2-x1;
    y2=1.5-y1;
    if ((x1*x1+y1*y1)>(x2*x2+y2*y2))
    {
        x1=x2;
        y1=y2;
    }
    if ((x1==0)&&(y1==0))
        PARAM_X=0.000001;
    th=atan2(y1,x1);
    if (th<M_PI/6)
        return(y1);
    else
    {
        y1=-sin(M_PI/3)*x1+cos(M_PI/3)*y1;
        return(fabs(y1));
    }
    }
    case 29: { // f_hetero_mf
        // f_hetero_mf
        double vx = PARAM_X, vy = PARAM_Y, vz = PARAM_Z;
        int ngen = (int)PARAM(5) & 3;
        double signal = (povNoise(vx, vy, vz, ngen) * 2.0 - 1.0) + PARAM(3);
        vx *= PARAM(1); vy *= PARAM(1); vz *= PARAM(1);
        double p1_2_mp0 = pow(PARAM(1), -PARAM(0)), ea = p1_2_mp0;
        for (int i = 1; i < PARAM(2); i++) {
            double inc = ((povNoise(vx, vy, vz, ngen) * 2.0 - 1.0) + PARAM(3)) * ea;
            for (int q = (int)PARAM(4); q > 0; --q) inc *= signal;
            signal += inc;
            vx *= PARAM(1); vy *= PARAM(1); vz *= PARAM(1);
            ea *= p1_2_mp0;
        }
        double rem = PARAM(2) - (int)PARAM(2);
        if (rem != 0.0) {
            double inc = ((povNoise(vx, vy, vz, ngen) * 2.0 - 1.0) + PARAM(3)) * ea;
            signal += rem * inc * signal;
        }
        return signal;
    }
    case 30: { // f_hunt_surface
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=-( 4*(x2+y2+z2-13)*(x2+y2+z2-13)*(x2+y2+z2-13) +
    27*(3*x2+y2-4*z2-12)*(3*x2+y2-4*z2-12)  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 31: { // f_hyperbolic_torus
    double r, ph,th,x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    ph=PARAM(1)*PARAM(1); th=PARAM(2)*PARAM(2);
    r=-( x2*x2 + 2*x2*y2 - 2*x2*z2 - 2*(ph+th)*x2 + y2*y2 -
    2*y2*z2 + 2*(ph-th)*y2 + z2*z2 + 2*(ph+th)*z2 + (ph-th)*(ph-th));
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 32: { // f_isect_ellipsoids
    double r,x2,y2,z2;
    x2=PARAM_X*PARAM_X; y2=PARAM_Y*PARAM_Y; z2=PARAM_Z*PARAM_Z;
    /* f= min (f1, f2, f3) */
    r=fmin(exp(-(x2*PARAM(0)+y2*PARAM(0)+z2)*PARAM(1)), exp(-(x2*PARAM(0)+y2+z2*PARAM(0))*PARAM(1)));
    r=fmin(r, exp(-(x2+y2*PARAM(0)+z2*PARAM(0))*PARAM(1)));
    return(PARAM(3)-r*PARAM(2));
    }
    case 33: { // f_kampyle_of_eudoxus
    double r, x2=PARAM_X*PARAM_X;
    r=-( (PARAM_Y*PARAM_Y + PARAM_Z*PARAM_Z) - PARAM(2)*PARAM(2) * x2*x2 +  PARAM(2)*PARAM(2) * PARAM(1)*PARAM(1) * x2  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 34: { // f_kampyle_of_eudoxus_2d
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, th;
    ROT2D(PARAM(3),PARAM(4),PARAM(5))
    r=-( y2  - PARAM(2)*PARAM(2) * x2*x2 +    PARAM(2)*PARAM(2) * PARAM(1)*PARAM(2) * x2  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 35: { // f_klein_bottle
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=-( (x2+y2+z2+2*PARAM_Y-1)*((x2+y2+z2-2*PARAM_Y-1)*(x2+y2+z2-2*PARAM_Y-1)-8*z2)+
    16*PARAM_X*PARAM_Z*(x2+y2+z2-2*PARAM_Y-1) );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 36: { // f_kummer_surface_v1
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=-( x2*x2+y2*y2+z2*z2-x2-y2-z2-x2*y2-x2*z2-y2*z2+1  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 37: { // f_kummer_surface_v2
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=-( x2*x2+y2*y2+z2*z2+PARAM(1)*(x2+y2+z2)+PARAM(2)*(x2*y2+x2*z2+y2*z2)+PARAM(3)*PARAM_X*PARAM_Y*PARAM_Z-1 );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 38: { // f_lemniscate_of_gerono
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=-(  x2*x2 - x2 + y2 + z2  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 39: { // f_lemniscate_of_gerono_2d
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, th;
    ROT2D(PARAM(3),PARAM(4),PARAM(5))
    r=-( y2 - PARAM(2)*PARAM(2) * PARAM(1)*PARAM(1) * x2 +   PARAM(2)*PARAM(2)*x2*x2  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 40: { // f_mesh1
    double th, ph, r, r2, temp;
    th = M_PI / PARAM(0);
    ph = M_PI / PARAM(1);
    r = fmod(PARAM_X, PARAM(0) * 2);
    if (r < 0)
        r += PARAM(0) * 2;
    r = fabs(r - PARAM(0)) * PARAM(2);
    r2 = (PARAM_Y - cos(PARAM_Z * ph) * PARAM(3)) * PARAM(4);
    temp = -sqrt(r2 * r2 + r * r);

    r = fmod(PARAM_X - PARAM(0), PARAM(0) * 2);
    if (r < 0)
        r += PARAM(0) * 2;
    r = fabs(r - PARAM(0)) * PARAM(2);
    r2 = (PARAM_Y + cos(PARAM_Z * ph) * PARAM(3)) * PARAM(4);
    temp = fmax(-sqrt(r2 * r2 + r * r), temp);

    r = fmod(PARAM_Z, PARAM(1) * 2);
    if (r < 0)
        r += PARAM(1) * 2;
    r = fabs(r - PARAM(1)) * PARAM(2);
    r2 = (PARAM_Y + cos(PARAM_X * th) * PARAM(3)) * PARAM(4);
    temp = fmax(-sqrt(r2 * r2 + r * r), temp);

    r = fmod(PARAM_Z - PARAM(1), PARAM(1) * 2);
    if (r < 0)
        r += PARAM(1) * 2;
    r = fabs(r - PARAM(1)) * PARAM(2);
    r2 = (PARAM_Y - cos(PARAM_X * th) * PARAM(3)) * PARAM(4);

    return (-fmax(-sqrt(r2 * r2 + r * r), temp));
    }
    case 41: { // f_mitre
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=-( 4*x2*(x2 + y2 + z2) - y2*(1 - y2 - z2)  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 42: { // f_nodal_cubic
    double r;
    r=-( PARAM_Y*PARAM_Y*PARAM_Y + PARAM_Z*PARAM_Z*PARAM_Z - 6*PARAM_Y*PARAM_Z );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 43: { // f_odd
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=( z2*x2 - z2*z2 - 2*PARAM_Z*x2 + 2*z2*PARAM_Z + x2 - z2 -
    (x2 - PARAM_Z)*(x2 - PARAM_Z) - y2*y2 - 2*y2*x2 - y2*z2 + 2*y2*PARAM_Z + y2  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 44: { // f_ovals_of_cassini
    double r, r2,x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r2 = (x2 + y2 + z2 + PARAM(1)*PARAM(1));
    r  = -(r2*r2 - PARAM(3)*PARAM(1)*PARAM(1)*(x2 + z2) - PARAM(2)*PARAM(2) );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 45: { // f_paraboloid
    double r;
    r=-( PARAM_X*PARAM_X - PARAM_Y + PARAM_Z*PARAM_Z);
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 46: { // f_parabolic_torus
    double r, ph,th, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    ph=PARAM(1)*PARAM(1); th=PARAM(2)*PARAM(2);
    r=-(  x2*x2 + 2*x2*y2 - 2*x2*PARAM_Z - (ph+th)*x2 + y2*y2 - 2*y2*PARAM_Z +
    (ph-th)*y2 + z2 + (ph+th)*PARAM_Z +  (ph-th)* (ph-th)  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 47: { // f_ph
    return( atan2(sqrt(PARAM_X*PARAM_X + PARAM_Z*PARAM_Z ),PARAM_Y) );
    }
    case 48: { // f_pillow
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=( x2*x2 + y2*y2 + z2*z2 - (x2 + y2 + z2)  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 49: { // f_piriform
    double r, x2=PARAM_X*PARAM_X;
    r=-( (x2*x2 - x2*PARAM_X) + PARAM_Y*PARAM_Y + PARAM_Z*PARAM_Z  );
    return( -fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 50: { // f_piriform_2d
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y,th;
    ROT2D(PARAM(4),PARAM(5),PARAM(6))
    r=-( PARAM_Y*PARAM_Y - PARAM(1) * PARAM(3)* PARAM(3) * x2*PARAM_X -  PARAM(2) * PARAM(3)*PARAM(3) * x2*x2  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 51: { // f_poly4
    /*  cylindrical shape   */
    double y2, temp;
    y2=PARAM_Y*PARAM_Y;
    temp=(PARAM(0)+PARAM(1)*PARAM_Y+PARAM(2)*y2 + PARAM(3)*y2*PARAM_Y +PARAM(4)*y2*y2);
    if (temp<-5.)
        temp=-5.;
    return (-temp+sqrt(PARAM_X*PARAM_X+PARAM_Z*PARAM_Z));
    }
    case 52: { // f_polytubes
    double x2,y2,z2,r,r2;
    int i;
    y2=PARAM_Y*PARAM_Y;
    r2=PARAM(1)+PARAM(2)*PARAM_Y+PARAM(3)*y2+PARAM(4)*y2*PARAM_Y+  PARAM(5)*y2*y2;
    r=-10000;
    for (i=0;i<(int)PARAM(0);i++)
    {
        x2 = PARAM_X - r2*sin(2*M_PI/PARAM(0)*i);
        z2 = PARAM_Z - r2*cos(2*M_PI/PARAM(0)*i);
        r= fmax(r,-sqrt( x2*x2 + z2*z2 ) );
    }
    return(-r);
    }
    case 53: { // f_quantum
    double r, th,temp;
    /*  well known function in quantum mechanics */
    if ((PARAM_X==0)&&(PARAM_Z==0))
        PARAM_X=1e-6;
    r=sqrt(PARAM_X*PARAM_X+PARAM_Z*PARAM_Z);
    th=cos(atan2(r,PARAM_Y));
    r=sqrt(r*r+PARAM_Y*PARAM_Y)*2.;
    temp=r*r*exp(-r*0.33333333)*(3.*th*th-1);
    return (temp*temp-12.0)*(-0.1);
    }
    case 54: { // f_quartic_paraboloid
    double r, x2=PARAM_X*PARAM_X, z2=PARAM_Z*PARAM_Z;
    r=-( x2*x2 + z2*z2 - PARAM_Y  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 55: { // f_quartic_saddle
    double r, x2=PARAM_X*PARAM_X, z2=PARAM_Z*PARAM_Z;
    r=-( x2*x2 - z2*z2 - PARAM_Y  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 56: { // f_quartic_cylinder
    double r, x2=PARAM_X*PARAM_X, z2=PARAM_Z*PARAM_Z;
    r=-( (x2 + z2) * PARAM_Y*PARAM_Y + PARAM(2)*PARAM(2) * (x2 + z2) - PARAM(2)*PARAM(2) * PARAM(1)*PARAM(1)  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 57: { // f_r
    return( sqrt(PARAM_X*PARAM_X + PARAM_Y*PARAM_Y + PARAM_Z*PARAM_Z ) );
    }
    case 58: { // f_ridge
        // f_ridge
        double px = PARAM_X, py = PARAM_Y, pz = PARAM_Z;
        int ngen = (int)PARAM(5) & 3;
        double Lambda = PARAM(0), l = Lambda;
        int Octaves = (int)PARAM(1);
        double Omega = PARAM(2), o = Omega;
        double off = PARAM(3), ridge = PARAM(4);
        double rscale = 1.0 / fmax(ridge, 1.0 - ridge);
        double scale  = 1.0 / fmax(off, 1.0 - off);
        double resid = PARAM(1) - (double)Octaves;
        double v = fabs(povNoise(px, py, pz, ngen) - ridge) * rscale;
        double value = (v - off);
        double tot = 1.0;
        for (int i = 2; i <= Octaves; i++) {
            double tx = px * l, ty = py * l, tz = pz * l;
            v = fabs(povNoise(tx, ty, tz, ngen) - ridge) * rscale;
            value += o * (v - off);
            tot += o; l *= Lambda; o *= Omega;
        }
        if (resid != 0.0) {
            double tx = px * l, ty = py * l, tz = pz * l;
            v = fabs(povNoise(tx, ty, tz, ngen) - ridge) * rscale;
            value += o * (v - off) * resid;
            tot += o * resid;
        }
        return value * scale / tot;
    }
    case 59: { // f_ridged_mf
        // f_ridged_mf (exponent array computed inline instead of cached)
        double px = PARAM_X, py = PARAM_Y, pz = PARAM_Z;
        int ngen = (int)PARAM(5) & 3;
        double H = PARAM(0), Lambda = PARAM(1), offset = PARAM(3), gain = PARAM(4);
        double eastep = pow(Lambda, -H), eacur = 1.0;
        double signal = povNoise(px, py, pz, ngen) * 2.0 - 1.0;
        if (signal < 0.0) signal = -signal;
        signal = offset - signal; signal *= signal;
        double result = signal, weight = 1.0;
        for (int i = 1; i < PARAM(2); i++) {
            px *= Lambda; py *= Lambda; pz *= Lambda;
            weight = signal * gain;
            if (weight > 1.0) weight = 1.0;
            if (weight < 0.0) weight = 0.0;
            signal = povNoise(px, py, pz, ngen) * 2.0 - 1.0;
            if (signal < 0.0) signal = -signal;
            signal = offset - signal; signal *= signal; signal *= weight;
            eacur *= eastep;
            result += signal * eacur;
        }
        return result;
    }
    case 60: { // f_rounded_box
    double x2, y2, z2, x3, y3, z3;

    x2 = PARAM(1) - PARAM(0);
    y2 = PARAM(2) - PARAM(0);
    z2 = PARAM(3) - PARAM(0);
    x3 = (PARAM_X < x2) ? 0 : (PARAM_X - x2);
    y3 = (PARAM_Y < y2) ? 0 : (PARAM_Y - y2);
    z3 = (PARAM_Z < z2) ? 0 : (PARAM_Z - z2);
    x2 = PARAM(0) - PARAM(1);
    y2 = PARAM(0) - PARAM(2);
    z2 = PARAM(0) - PARAM(3);
    PARAM_X = (PARAM_X > x2) ? 0 : (x2 - PARAM_X);
    PARAM_Y = (PARAM_Y > y2) ? 0 : (y2 - PARAM_Y);
    PARAM_Z = (PARAM_Z > z2) ? 0 : (z2 - PARAM_Z);
    PARAM_X = fmax(PARAM_X, x3);
    PARAM_Y = fmax(PARAM_Y, y3);
    PARAM_Z = fmax(PARAM_Z, z3);

    return (-PARAM(0) + sqrt(PARAM_X * PARAM_X + PARAM_Y * PARAM_Y + PARAM_Z * PARAM_Z) - 1e-6);
    }
    case 61: { // f_sphere
    return (-PARAM(0) + sqrt(PARAM_X * PARAM_X + PARAM_Y * PARAM_Y + PARAM_Z * PARAM_Z));
    }
    case 62: { // f_spikes
    double r,x2,y2,z2;
    x2=PARAM_X*PARAM_X; y2=PARAM_Y*PARAM_Y; z2=PARAM_Z*PARAM_Z;
    r= exp(-(x2+y2+z2)*PARAM(3))*PARAM(4)          -exp(-(x2*PARAM(0)+y2*PARAM(0)+z2)*PARAM(1))
      -exp(-(x2*PARAM(0)+y2+z2*PARAM(0))*PARAM(1)) -exp(-(x2+y2*PARAM(0)+z2*PARAM(0))*PARAM(1));
    return(-r*PARAM(2));
    }
    case 63: { // f_spikes_2d
    /*  2-D distribution */
    return(-( PARAM(0)* cos(PARAM(1)*PARAM_X) * cos(PARAM(2)*PARAM_Z) * exp(- PARAM(3)*(PARAM_X*PARAM_X+PARAM_Z*PARAM_Z)) -PARAM_Y));
    }
    case 64: { // f_spiral
    double r, r2, th, temp;
    /* spiral shape                *
     *                             */
    r = sqrt(PARAM_X * PARAM_X + PARAM_Z * PARAM_Z);
    if ((PARAM_X == 0) && (PARAM_Z == 0))
        PARAM_X = 0.000001;
    th = atan2(PARAM_Z, PARAM_X);
    r = r + PARAM(0) * th / TWO_M_PI;
    r2 = fmod(r, PARAM(0)) - PARAM(0) * 0.5;

    if (PARAM(5) == 1)
        r2 = sqrt(r2 * r2 + PARAM_Y * PARAM_Y);
    else if (PARAM(5) != 0)
    {
        temp = 2 / PARAM(5);
        r2 = pow((pow(fabs(r2), temp) + pow(fabs(PARAM_Y), temp)), 1. / temp);
    }
    else
        r2 = fmax(fabs(r2), fabs(PARAM_Y));

    r = sqrt(PARAM_X * PARAM_X + PARAM_Y * PARAM_Y + PARAM_Z * PARAM_Z);

    return (-fmin(PARAM(2) - r, PARAM(1) - fmin(r2, r)));
    }
    case 65: { // f_steiners_roman
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=-( x2*y2 + x2*z2 + y2*z2 + PARAM_X*PARAM_Y*PARAM_Z  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 66: { // f_strophoid
    double r, r2,x2=PARAM_X*PARAM_X;
    r2=PARAM(3)*PARAM(3);
    r=-((PARAM(2) - PARAM_X)*(PARAM_Y*PARAM_Y + PARAM_Z*PARAM_Z) - r2*PARAM(1)*x2 - r2*x2*PARAM_X );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 67: { // f_strophoid_2d
    double r, r2,x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, th;
    ROT2D(PARAM(4),PARAM(5),PARAM(6))
    r2=PARAM(3)*PARAM(3);
    r=-( (PARAM(2) - PARAM_X)*y2  - r2*PARAM(1)*x2 -  r2*x2*PARAM_X  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 68: { // f_superellipsoid
    double p = 2 / PARAM(0), n = 1 / PARAM(1);

    return 1 - pow((pow((pow(fabs(PARAM_X), p) + pow(fabs(PARAM_Y), p)), PARAM(0) * n) + pow(fabs(PARAM_Z), 2 * n)), PARAM(1) *.5);
    }
    case 69: { // f_th
    return( atan2(PARAM_X,PARAM_Z) );
    }
    case 70: { // f_torus
    PARAM_X = sqrt(PARAM_X * PARAM_X + PARAM_Z * PARAM_Z) - PARAM(0);

    return -PARAM(1) + sqrt(PARAM_X * PARAM_X + PARAM_Y * PARAM_Y);
    }
    case 71: { // f_torus2
    double r, ph,th,x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    ph=PARAM(1)*PARAM(1); th=PARAM(2)*PARAM(2);
    r=-( x2*x2 + y2*y2 + z2*z2 + 2*x2*y2 + 2*x2*z2 + 2*y2*z2 -2* (ph + th)* x2 + 2* (ph - th)* y2 -2* (ph + th)* z2 + (ph - th)*(ph - th)  );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 72: { // f_torus_gumdrop
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, z2=PARAM_Z*PARAM_Z;
    r=-( 4*(x2*x2 + (y2 + z2)*(y2 + z2)) + 17 * x2 * (y2 + z2) - 20 * (x2 + y2 + z2) + 17);
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 73: { // f_umbrella
    double r;
    r=-( PARAM_X*PARAM_X - PARAM_Y*PARAM_Z*PARAM_Z );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 74: { // f_witch_of_agnesi
    double r;
    r=-( PARAM(1) * (PARAM_Y - 1) + (PARAM_X*PARAM_X + PARAM_Z*PARAM_Z) * PARAM_Y   );
    return( fmin(10., fmax(PARAM(0)*r,-10.)) );
    }
    case 75: { // f_witch_of_agnesi_2d
    double r, x2=PARAM_X*PARAM_X, y2=PARAM_Y*PARAM_Y, th;
    ROT2D(PARAM(3),PARAM(4),PARAM(5))
    r=-( PARAM(1)*PARAM(1) * PARAM_Y + x2 * PARAM_Y - PARAM(2)  );
    return( fmin(10.0, fmax(PARAM(0)*r,-10.0)) );
    }
    case 76: { // f_noise3d
        // f_noise3d: POV Noise() with the scene-default generator (RangeCorrected=2)
        return povNoise(PARAM_X, PARAM_Y, PARAM_Z, 2);
    }
    case 78: { // f_noise_generator
        // f_noise_generator: generator selected by P0 (& 3)
        int ngen = (int)PARAM(0) & 3;
        return povNoise(PARAM_X, PARAM_Y, PARAM_Z, ngen);
    }
    default: break;
    }
#undef PARAM_X
#undef PARAM_Y
#undef PARAM_Z
#undef PARAM
    return 0.0;
}

#undef ROT2D

// Total argument count (including x,y,z) for POV internal function `id`, or 0 if
// unsupported.  Device-safe so the VM can pop the right number of stack slots.
POV_HD inline int povFnArity(int id) {
    switch (id) {
    case 0: return 8; // f_algbr_cyl1
    case 1: return 8; // f_algbr_cyl2
    case 2: return 8; // f_algbr_cyl3
    case 3: return 8; // f_algbr_cyl4
    case 4: return 5; // f_bicorn
    case 5: return 5; // f_bifolia
    case 6: return 8; // f_blob
    case 7: return 7; // f_blob2
    case 8: return 5; // f_boy_surface
    case 9: return 4; // f_comma
    case 10: return 7; // f_cross_ellipsoids
    case 11: return 4; // f_crossed_trough
    case 12: return 4; // f_cubic_saddle
    case 13: return 4; // f_cushion
    case 14: return 4; // f_devils_curve
    case 15: return 9; // f_devils_curve_2d
    case 16: return 9; // f_dupin_cyclid
    case 17: return 6; // f_ellipsoid
    case 18: return 4; // f_enneper
    case 19: return 7; // f_flange_cover
    case 20: return 6; // f_folium_surface
    case 21: return 9; // f_folium_surface_2d
    case 22: return 4; // f_glob
    case 23: return 4; // f_heart
    case 24: return 13; // f_helical_torus
    case 25: return 10; // f_helix1
    case 26: return 10; // f_helix2
    case 27: return 4; // f_hex_x
    case 28: return 4; // f_hex_y
    case 29: return 9; // f_hetero_mf
    case 30: return 4; // f_hunt_surface
    case 31: return 6; // f_hyperbolic_torus
    case 32: return 7; // f_isect_ellipsoids
    case 33: return 6; // f_kampyle_of_eudoxus
    case 34: return 9; // f_kampyle_of_eudoxus_2d
    case 35: return 4; // f_klein_bottle
    case 36: return 4; // f_kummer_surface_v1
    case 37: return 7; // f_kummer_surface_v2
    case 38: return 4; // f_lemniscate_of_gerono
    case 39: return 9; // f_lemniscate_of_gerono_2d
    case 40: return 8; // f_mesh1
    case 41: return 4; // f_mitre
    case 42: return 4; // f_nodal_cubic
    case 43: return 4; // f_odd
    case 44: return 7; // f_ovals_of_cassini
    case 45: return 4; // f_paraboloid
    case 46: return 6; // f_parabolic_torus
    case 47: return 3; // f_ph
    case 48: return 4; // f_pillow
    case 49: return 4; // f_piriform
    case 50: return 10; // f_piriform_2d
    case 51: return 8; // f_poly4
    case 52: return 9; // f_polytubes
    case 53: return 4; // f_quantum
    case 54: return 4; // f_quartic_paraboloid
    case 55: return 4; // f_quartic_saddle
    case 56: return 6; // f_quartic_cylinder
    case 57: return 3; // f_r
    case 58: return 9; // f_ridge
    case 59: return 9; // f_ridged_mf
    case 60: return 7; // f_rounded_box
    case 61: return 4; // f_sphere
    case 62: return 8; // f_spikes
    case 63: return 7; // f_spikes_2d
    case 64: return 9; // f_spiral
    case 65: return 4; // f_steiners_roman
    case 66: return 7; // f_strophoid
    case 67: return 10; // f_strophoid_2d
    case 68: return 5; // f_superellipsoid
    case 69: return 3; // f_th
    case 70: return 5; // f_torus
    case 71: return 6; // f_torus2
    case 72: return 4; // f_torus_gumdrop
    case 73: return 4; // f_umbrella
    case 74: return 5; // f_witch_of_agnesi
    case 75: return 9; // f_witch_of_agnesi_2d
    case 76: return 3; // f_noise3d
    case 78: return 4; // f_noise_generator
    default: return 0;
    }
}

// ---- name table (parser side) -----------------------------------------------
// Plain host inlines (not __device__).  No __CUDA_ARCH__ guard: under nvcc the
// host-side funcOp() in pattern.h references povFnLookup during the device pass
// too (it is parsed, though only host-compiled), so the symbol must stay visible.
#include <string.h>
struct PovFnInfo { const char* name; int id; int arity; };
inline const PovFnInfo* povFnTable(int& count) {
    static const PovFnInfo T[] = {
    { "f_algbr_cyl1", 0, 8 },
    { "f_algbr_cyl2", 1, 8 },
    { "f_algbr_cyl3", 2, 8 },
    { "f_algbr_cyl4", 3, 8 },
    { "f_bicorn", 4, 5 },
    { "f_bifolia", 5, 5 },
    { "f_blob", 6, 8 },
    { "f_blob2", 7, 7 },
    { "f_boy_surface", 8, 5 },
    { "f_comma", 9, 4 },
    { "f_cross_ellipsoids", 10, 7 },
    { "f_crossed_trough", 11, 4 },
    { "f_cubic_saddle", 12, 4 },
    { "f_cushion", 13, 4 },
    { "f_devils_curve", 14, 4 },
    { "f_devils_curve_2d", 15, 9 },
    { "f_dupin_cyclid", 16, 9 },
    { "f_ellipsoid", 17, 6 },
    { "f_enneper", 18, 4 },
    { "f_flange_cover", 19, 7 },
    { "f_folium_surface", 20, 6 },
    { "f_folium_surface_2d", 21, 9 },
    { "f_glob", 22, 4 },
    { "f_heart", 23, 4 },
    { "f_helical_torus", 24, 13 },
    { "f_helix1", 25, 10 },
    { "f_helix2", 26, 10 },
    { "f_hex_x", 27, 4 },
    { "f_hex_y", 28, 4 },
    { "f_hetero_mf", 29, 9 },
    { "f_hunt_surface", 30, 4 },
    { "f_hyperbolic_torus", 31, 6 },
    { "f_isect_ellipsoids", 32, 7 },
    { "f_kampyle_of_eudoxus", 33, 6 },
    { "f_kampyle_of_eudoxus_2d", 34, 9 },
    { "f_klein_bottle", 35, 4 },
    { "f_kummer_surface_v1", 36, 4 },
    { "f_kummer_surface_v2", 37, 7 },
    { "f_lemniscate_of_gerono", 38, 4 },
    { "f_lemniscate_of_gerono_2d", 39, 9 },
    { "f_mesh1", 40, 8 },
    { "f_mitre", 41, 4 },
    { "f_nodal_cubic", 42, 4 },
    { "f_odd", 43, 4 },
    { "f_ovals_of_cassini", 44, 7 },
    { "f_paraboloid", 45, 4 },
    { "f_parabolic_torus", 46, 6 },
    { "f_ph", 47, 3 },
    { "f_pillow", 48, 4 },
    { "f_piriform", 49, 4 },
    { "f_piriform_2d", 50, 10 },
    { "f_poly4", 51, 8 },
    { "f_polytubes", 52, 9 },
    { "f_quantum", 53, 4 },
    { "f_quartic_paraboloid", 54, 4 },
    { "f_quartic_saddle", 55, 4 },
    { "f_quartic_cylinder", 56, 6 },
    { "f_r", 57, 3 },
    { "f_ridge", 58, 9 },
    { "f_ridged_mf", 59, 9 },
    { "f_rounded_box", 60, 7 },
    { "f_sphere", 61, 4 },
    { "f_spikes", 62, 8 },
    { "f_spikes_2d", 63, 7 },
    { "f_spiral", 64, 9 },
    { "f_steiners_roman", 65, 4 },
    { "f_strophoid", 66, 7 },
    { "f_strophoid_2d", 67, 10 },
    { "f_superellipsoid", 68, 5 },
    { "f_th", 69, 3 },
    { "f_torus", 70, 5 },
    { "f_torus2", 71, 6 },
    { "f_torus_gumdrop", 72, 4 },
    { "f_umbrella", 73, 4 },
    { "f_witch_of_agnesi", 74, 5 },
    { "f_witch_of_agnesi_2d", 75, 9 },
    { "f_noise3d", 76, 3 },
    { "f_noise_generator", 78, 4 },
    };
    count = (int)(sizeof(T) / sizeof(T[0]));
    return T;
}
// Look up an SDL name; on success fills id (POV internal id) and arity (total
// args including x,y,z).  Returns false if not a supported POV function.
inline bool povFnLookup(const char* name, int& id, int& arity) {
    int n; const PovFnInfo* T = povFnTable(n);
    for (int i = 0; i < n; ++i)
        if (strcmp(name, T[i].name) == 0) { id = T[i].id; arity = T[i].arity; return true; }
    return false;
}
