// GENERATED by loom.grammar.emit_cpp from a .epeg grammar -- DO NOT EDIT.
// Regenerate:  python -m loom.grammar.emit_cpp <grammar>.epeg ftsl_scene
//
// Rebuilds the compiled GPDA graph + auto-lexer table for the tokenized
// C++ engine (gpda_tok), so the .epeg stays the single source of truth.
#include "tokenized.hpp"
#include "gpda_lexer.hpp"

namespace ftsl_gen {

gpda_tok::Graph build_ftsl_scene_graph() {
    using gpda_tok::Graph;
    using gpda_tok::NodeType;
    Graph g;
    g.nodes.resize(193);

    g.nodes[0].type = NodeType::RuleStart;
    g.nodes[0].rule_name = "scene_file";
    g.nodes[0].links = {59};

    g.nodes[1].type = NodeType::RuleEnd;
    g.nodes[1].rule_name = "scene_file";

    g.nodes[2].type = NodeType::RuleStart;
    g.nodes[2].rule_name = "item";
    g.nodes[2].links = {61, 62};

    g.nodes[3].type = NodeType::RuleEnd;
    g.nodes[3].rule_name = "item";

    g.nodes[4].type = NodeType::RuleStart;
    g.nodes[4].rule_name = "top_block";
    g.nodes[4].links = {63, 64, 65, 66, 67};

    g.nodes[5].type = NodeType::RuleEnd;
    g.nodes[5].rule_name = "top_block";

    g.nodes[6].type = NodeType::RuleStart;
    g.nodes[6].rule_name = "prefer_block";
    g.nodes[6].links = {68};

    g.nodes[7].type = NodeType::RuleEnd;
    g.nodes[7].rule_name = "prefer_block";

    g.nodes[8].type = NodeType::RuleStart;
    g.nodes[8].rule_name = "block_list";
    g.nodes[8].links = {76};

    g.nodes[9].type = NodeType::RuleEnd;
    g.nodes[9].rule_name = "block_list";

    g.nodes[10].type = NodeType::RuleStart;
    g.nodes[10].rule_name = "nlq";
    g.nodes[10].links = {82};

    g.nodes[11].type = NodeType::RuleEnd;
    g.nodes[11].rule_name = "nlq";

    g.nodes[12].type = NodeType::RuleStart;
    g.nodes[12].rule_name = "record_decl";
    g.nodes[12].links = {84};

    g.nodes[13].type = NodeType::RuleEnd;
    g.nodes[13].rule_name = "record_decl";

    g.nodes[14].type = NodeType::RuleStart;
    g.nodes[14].rule_name = "range_word";
    g.nodes[14].links = {92, 93, 94, 95};

    g.nodes[15].type = NodeType::RuleEnd;
    g.nodes[15].rule_name = "range_word";

    g.nodes[16].type = NodeType::RuleStart;
    g.nodes[16].rule_name = "record_body";
    g.nodes[16].links = {96};

    g.nodes[17].type = NodeType::RuleEnd;
    g.nodes[17].rule_name = "record_body";

    g.nodes[18].type = NodeType::RuleStart;
    g.nodes[18].rule_name = "rec_item";
    g.nodes[18].links = {101, 102};

    g.nodes[19].type = NodeType::RuleEnd;
    g.nodes[19].rule_name = "rec_item";

    g.nodes[20].type = NodeType::RuleStart;
    g.nodes[20].rule_name = "record_line";
    g.nodes[20].links = {103};

    g.nodes[21].type = NodeType::RuleEnd;
    g.nodes[21].rule_name = "record_line";

    g.nodes[22].type = NodeType::RuleStart;
    g.nodes[22].rule_name = "stop_word";
    g.nodes[22].links = {107, 108, 109, 110};

    g.nodes[23].type = NodeType::RuleEnd;
    g.nodes[23].rule_name = "stop_word";

    g.nodes[24].type = NodeType::RuleStart;
    g.nodes[24].rule_name = "spectrum_decl";
    g.nodes[24].links = {111};

    g.nodes[25].type = NodeType::RuleEnd;
    g.nodes[25].rule_name = "spectrum_decl";

    g.nodes[26].type = NodeType::RuleStart;
    g.nodes[26].rule_name = "assign_header";
    g.nodes[26].links = {120};

    g.nodes[27].type = NodeType::RuleEnd;
    g.nodes[27].rule_name = "assign_header";

    g.nodes[28].type = NodeType::RuleStart;
    g.nodes[28].rule_name = "plain_header";
    g.nodes[28].links = {127};

    g.nodes[29].type = NodeType::RuleEnd;
    g.nodes[29].rule_name = "plain_header";

    g.nodes[30].type = NodeType::RuleStart;
    g.nodes[30].rule_name = "subtype";
    g.nodes[30].links = {135};

    g.nodes[31].type = NodeType::RuleEnd;
    g.nodes[31].rule_name = "subtype";

    g.nodes[32].type = NodeType::RuleStart;
    g.nodes[32].rule_name = "brace_body";
    g.nodes[32].links = {136};

    g.nodes[33].type = NodeType::RuleEnd;
    g.nodes[33].rule_name = "brace_body";

    g.nodes[34].type = NodeType::RuleStart;
    g.nodes[34].rule_name = "body_item";
    g.nodes[34].links = {141, 142};

    g.nodes[35].type = NodeType::RuleEnd;
    g.nodes[35].rule_name = "body_item";

    g.nodes[36].type = NodeType::RuleStart;
    g.nodes[36].rule_name = "stmt";
    g.nodes[36].links = {143};

    g.nodes[37].type = NodeType::RuleEnd;
    g.nodes[37].rule_name = "stmt";

    g.nodes[38].type = NodeType::RuleStart;
    g.nodes[38].rule_name = "key_tok";
    g.nodes[38].links = {145, 146, 147};

    g.nodes[39].type = NodeType::RuleEnd;
    g.nodes[39].rule_name = "key_tok";

    g.nodes[40].type = NodeType::RuleStart;
    g.nodes[40].rule_name = "value";
    g.nodes[40].links = {148, 149};

    g.nodes[41].type = NodeType::RuleEnd;
    g.nodes[41].rule_name = "value";

    g.nodes[42].type = NodeType::RuleStart;
    g.nodes[42].rule_name = "override_val";
    g.nodes[42].links = {150};

    g.nodes[43].type = NodeType::RuleEnd;
    g.nodes[43].rule_name = "override_val";

    g.nodes[44].type = NodeType::RuleStart;
    g.nodes[44].rule_name = "rhs";
    g.nodes[44].links = {157, 158, 159, 160};

    g.nodes[45].type = NodeType::RuleEnd;
    g.nodes[45].rule_name = "rhs";

    g.nodes[46].type = NodeType::RuleStart;
    g.nodes[46].rule_name = "normal_val";
    g.nodes[46].links = {162};

    g.nodes[47].type = NodeType::RuleEnd;
    g.nodes[47].rule_name = "normal_val";

    g.nodes[48].type = NodeType::RuleStart;
    g.nodes[48].rule_name = "val_head";
    g.nodes[48].links = {173, 174, 175, 176};

    g.nodes[49].type = NodeType::RuleEnd;
    g.nodes[49].rule_name = "val_head";

    g.nodes[50].type = NodeType::RuleStart;
    g.nodes[50].rule_name = "cont";
    g.nodes[50].links = {177, 178, 179};

    g.nodes[51].type = NodeType::RuleEnd;
    g.nodes[51].rule_name = "cont";

    g.nodes[52].type = NodeType::RuleStart;
    g.nodes[52].rule_name = "selector";
    g.nodes[52].links = {180};

    g.nodes[53].type = NodeType::RuleEnd;
    g.nodes[53].rule_name = "selector";

    g.nodes[54].type = NodeType::RuleStart;
    g.nodes[54].rule_name = "sel_word";
    g.nodes[54].links = {185, 186, 187};

    g.nodes[55].type = NodeType::RuleEnd;
    g.nodes[55].rule_name = "sel_word";

    g.nodes[56].type = NodeType::RuleStart;
    g.nodes[56].rule_name = "block";
    g.nodes[56].links = {188};

    g.nodes[57].type = NodeType::RuleEnd;
    g.nodes[57].rule_name = "block";

    g.nodes[58].type = NodeType::RuleRef;
    g.nodes[58].value = "item";
    g.nodes[58].links = {59};

    g.nodes[59].type = NodeType::Split;
    g.nodes[59].links = {58, 60};

    g.nodes[60].type = NodeType::Split;
    g.nodes[60].links = {1};

    g.nodes[61].type = NodeType::MatchTok;
    g.nodes[61].value = "NEWLINE";
    g.nodes[61].links = {3};

    g.nodes[62].type = NodeType::RuleRef;
    g.nodes[62].value = "top_block";
    g.nodes[62].links = {3};

    g.nodes[63].type = NodeType::RuleRef;
    g.nodes[63].value = "prefer_block";
    g.nodes[63].links = {5};

    g.nodes[64].type = NodeType::RuleRef;
    g.nodes[64].value = "record_decl";
    g.nodes[64].links = {5};

    g.nodes[65].type = NodeType::RuleRef;
    g.nodes[65].value = "spectrum_decl";
    g.nodes[65].links = {5};

    g.nodes[66].type = NodeType::RuleRef;
    g.nodes[66].value = "assign_header";
    g.nodes[66].links = {5};

    g.nodes[67].type = NodeType::RuleRef;
    g.nodes[67].value = "plain_header";
    g.nodes[67].links = {5};

    g.nodes[68].type = NodeType::MatchStr;
    g.nodes[68].value = "prefer";
    g.nodes[68].links = {69};

    g.nodes[69].type = NodeType::RuleRef;
    g.nodes[69].value = "nlq";
    g.nodes[69].links = {70};

    g.nodes[70].type = NodeType::RuleRef;
    g.nodes[70].value = "block_list";
    g.nodes[70].links = {74};

    g.nodes[71].type = NodeType::MatchStr;
    g.nodes[71].value = "else";
    g.nodes[71].links = {72};

    g.nodes[72].type = NodeType::RuleRef;
    g.nodes[72].value = "nlq";
    g.nodes[72].links = {73};

    g.nodes[73].type = NodeType::RuleRef;
    g.nodes[73].value = "block_list";
    g.nodes[73].links = {74};

    g.nodes[74].type = NodeType::Split;
    g.nodes[74].links = {71, 75};

    g.nodes[75].type = NodeType::Split;
    g.nodes[75].links = {7};

    g.nodes[76].type = NodeType::MatchStr;
    g.nodes[76].value = "{";
    g.nodes[76].links = {78};

    g.nodes[77].type = NodeType::RuleRef;
    g.nodes[77].value = "item";
    g.nodes[77].links = {78};

    g.nodes[78].type = NodeType::Split;
    g.nodes[78].links = {77, 79};

    g.nodes[79].type = NodeType::Split;
    g.nodes[79].links = {80};

    g.nodes[80].type = NodeType::MatchStr;
    g.nodes[80].value = "}";
    g.nodes[80].links = {9};

    g.nodes[81].type = NodeType::MatchTok;
    g.nodes[81].value = "NEWLINE";
    g.nodes[81].links = {82};

    g.nodes[82].type = NodeType::Split;
    g.nodes[82].links = {81, 83};

    g.nodes[83].type = NodeType::Split;
    g.nodes[83].links = {11};

    g.nodes[84].type = NodeType::MatchTok;
    g.nodes[84].value = "WORD";
    g.nodes[84].links = {85};

    g.nodes[85].type = NodeType::MatchStr;
    g.nodes[85].value = "=";
    g.nodes[85].links = {86};

    g.nodes[86].type = NodeType::MatchStr;
    g.nodes[86].value = "range";
    g.nodes[86].links = {88};

    g.nodes[87].type = NodeType::RuleRef;
    g.nodes[87].value = "range_word";
    g.nodes[87].links = {88};

    g.nodes[88].type = NodeType::Split;
    g.nodes[88].links = {87, 89};

    g.nodes[89].type = NodeType::Split;
    g.nodes[89].links = {90};

    g.nodes[90].type = NodeType::RuleRef;
    g.nodes[90].value = "nlq";
    g.nodes[90].links = {91};

    g.nodes[91].type = NodeType::RuleRef;
    g.nodes[91].value = "record_body";
    g.nodes[91].links = {13};

    g.nodes[92].type = NodeType::MatchTok;
    g.nodes[92].value = "NUMWORD";
    g.nodes[92].links = {15};

    g.nodes[93].type = NodeType::MatchTok;
    g.nodes[93].value = "KVWORD";
    g.nodes[93].links = {15};

    g.nodes[94].type = NodeType::MatchTok;
    g.nodes[94].value = "STRING";
    g.nodes[94].links = {15};

    g.nodes[95].type = NodeType::MatchTok;
    g.nodes[95].value = "WORD";
    g.nodes[95].links = {15};

    g.nodes[96].type = NodeType::MatchStr;
    g.nodes[96].value = "[";
    g.nodes[96].links = {98};

    g.nodes[97].type = NodeType::RuleRef;
    g.nodes[97].value = "rec_item";
    g.nodes[97].links = {98};

    g.nodes[98].type = NodeType::Split;
    g.nodes[98].links = {97, 99};

    g.nodes[99].type = NodeType::Split;
    g.nodes[99].links = {100};

    g.nodes[100].type = NodeType::MatchStr;
    g.nodes[100].value = "]";
    g.nodes[100].links = {17};

    g.nodes[101].type = NodeType::MatchTok;
    g.nodes[101].value = "NEWLINE";
    g.nodes[101].links = {19};

    g.nodes[102].type = NodeType::RuleRef;
    g.nodes[102].value = "record_line";
    g.nodes[102].links = {19};

    g.nodes[103].type = NodeType::MatchTok;
    g.nodes[103].value = "WORD";
    g.nodes[103].links = {105};

    g.nodes[104].type = NodeType::RuleRef;
    g.nodes[104].value = "stop_word";
    g.nodes[104].links = {105};

    g.nodes[105].type = NodeType::Split;
    g.nodes[105].links = {104, 106};

    g.nodes[106].type = NodeType::Split;
    g.nodes[106].links = {21};

    g.nodes[107].type = NodeType::MatchTok;
    g.nodes[107].value = "NUMWORD";
    g.nodes[107].links = {23};

    g.nodes[108].type = NodeType::MatchTok;
    g.nodes[108].value = "KVWORD";
    g.nodes[108].links = {23};

    g.nodes[109].type = NodeType::MatchTok;
    g.nodes[109].value = "STRING";
    g.nodes[109].links = {23};

    g.nodes[110].type = NodeType::MatchTok;
    g.nodes[110].value = "WORD";
    g.nodes[110].links = {23};

    g.nodes[111].type = NodeType::MatchStr;
    g.nodes[111].value = "spectrum";
    g.nodes[111].links = {113};

    g.nodes[112].type = NodeType::MatchTok;
    g.nodes[112].value = "STRING";
    g.nodes[112].links = {114};

    g.nodes[113].type = NodeType::Split;
    g.nodes[113].links = {112, 114};

    g.nodes[114].type = NodeType::Split;
    g.nodes[114].links = {116};

    g.nodes[115].type = NodeType::RuleRef;
    g.nodes[115].value = "subtype";
    g.nodes[115].links = {117};

    g.nodes[116].type = NodeType::Split;
    g.nodes[116].links = {115, 117};

    g.nodes[117].type = NodeType::Split;
    g.nodes[117].links = {118};

    g.nodes[118].type = NodeType::MatchStr;
    g.nodes[118].value = "=";
    g.nodes[118].links = {119};

    g.nodes[119].type = NodeType::RuleRef;
    g.nodes[119].value = "value";
    g.nodes[119].links = {25};

    g.nodes[120].type = NodeType::MatchTok;
    g.nodes[120].value = "WORD";
    g.nodes[120].links = {121};

    g.nodes[121].type = NodeType::MatchStr;
    g.nodes[121].value = "=";
    g.nodes[121].links = {122};

    g.nodes[122].type = NodeType::MatchTok;
    g.nodes[122].value = "WORD";
    g.nodes[122].links = {124};

    g.nodes[123].type = NodeType::RuleRef;
    g.nodes[123].value = "subtype";
    g.nodes[123].links = {125};

    g.nodes[124].type = NodeType::Split;
    g.nodes[124].links = {123, 125};

    g.nodes[125].type = NodeType::Split;
    g.nodes[125].links = {126};

    g.nodes[126].type = NodeType::RuleRef;
    g.nodes[126].value = "brace_body";
    g.nodes[126].links = {27};

    g.nodes[127].type = NodeType::MatchTok;
    g.nodes[127].value = "WORD";
    g.nodes[127].links = {129};

    g.nodes[128].type = NodeType::MatchTok;
    g.nodes[128].value = "STRING";
    g.nodes[128].links = {130};

    g.nodes[129].type = NodeType::Split;
    g.nodes[129].links = {128, 130};

    g.nodes[130].type = NodeType::Split;
    g.nodes[130].links = {132};

    g.nodes[131].type = NodeType::RuleRef;
    g.nodes[131].value = "subtype";
    g.nodes[131].links = {133};

    g.nodes[132].type = NodeType::Split;
    g.nodes[132].links = {131, 133};

    g.nodes[133].type = NodeType::Split;
    g.nodes[133].links = {134};

    g.nodes[134].type = NodeType::RuleRef;
    g.nodes[134].value = "brace_body";
    g.nodes[134].links = {29};

    g.nodes[135].type = NodeType::MatchTok;
    g.nodes[135].value = "WORD";
    g.nodes[135].links = {31};

    g.nodes[136].type = NodeType::MatchStr;
    g.nodes[136].value = "{";
    g.nodes[136].links = {138};

    g.nodes[137].type = NodeType::RuleRef;
    g.nodes[137].value = "body_item";
    g.nodes[137].links = {138};

    g.nodes[138].type = NodeType::Split;
    g.nodes[138].links = {137, 139};

    g.nodes[139].type = NodeType::Split;
    g.nodes[139].links = {140};

    g.nodes[140].type = NodeType::MatchStr;
    g.nodes[140].value = "}";
    g.nodes[140].links = {33};

    g.nodes[141].type = NodeType::MatchTok;
    g.nodes[141].value = "NEWLINE";
    g.nodes[141].links = {35};

    g.nodes[142].type = NodeType::RuleRef;
    g.nodes[142].value = "stmt";
    g.nodes[142].links = {35};

    g.nodes[143].type = NodeType::RuleRef;
    g.nodes[143].value = "key_tok";
    g.nodes[143].links = {144};

    g.nodes[144].type = NodeType::RuleRef;
    g.nodes[144].value = "value";
    g.nodes[144].links = {37};

    g.nodes[145].type = NodeType::MatchTok;
    g.nodes[145].value = "WORD";
    g.nodes[145].links = {39};

    g.nodes[146].type = NodeType::MatchTok;
    g.nodes[146].value = "NUMWORD";
    g.nodes[146].links = {39};

    g.nodes[147].type = NodeType::MatchTok;
    g.nodes[147].value = "KVWORD";
    g.nodes[147].links = {39};

    g.nodes[148].type = NodeType::RuleRef;
    g.nodes[148].value = "override_val";
    g.nodes[148].links = {41};

    g.nodes[149].type = NodeType::RuleRef;
    g.nodes[149].value = "normal_val";
    g.nodes[149].links = {41};

    g.nodes[150].type = NodeType::MatchStr;
    g.nodes[150].value = "=";
    g.nodes[150].links = {152};

    g.nodes[151].type = NodeType::RuleRef;
    g.nodes[151].value = "rhs";
    g.nodes[151].links = {153};

    g.nodes[152].type = NodeType::Split;
    g.nodes[152].links = {151, 153};

    g.nodes[153].type = NodeType::Split;
    g.nodes[153].links = {155};

    g.nodes[154].type = NodeType::RuleRef;
    g.nodes[154].value = "selector";
    g.nodes[154].links = {156};

    g.nodes[155].type = NodeType::Split;
    g.nodes[155].links = {154, 156};

    g.nodes[156].type = NodeType::Split;
    g.nodes[156].links = {43};

    g.nodes[157].type = NodeType::MatchTok;
    g.nodes[157].value = "STRING";
    g.nodes[157].links = {45};

    g.nodes[158].type = NodeType::MatchTok;
    g.nodes[158].value = "NUMWORD";
    g.nodes[158].links = {45};

    g.nodes[159].type = NodeType::MatchTok;
    g.nodes[159].value = "KVWORD";
    g.nodes[159].links = {45};

    g.nodes[160].type = NodeType::MatchTok;
    g.nodes[160].value = "WORD";
    g.nodes[160].links = {45};

    g.nodes[161].type = NodeType::RuleRef;
    g.nodes[161].value = "val_head";
    g.nodes[161].links = {163};

    g.nodes[162].type = NodeType::Split;
    g.nodes[162].links = {161, 163};

    g.nodes[163].type = NodeType::Split;
    g.nodes[163].links = {165};

    g.nodes[164].type = NodeType::RuleRef;
    g.nodes[164].value = "cont";
    g.nodes[164].links = {165};

    g.nodes[165].type = NodeType::Split;
    g.nodes[165].links = {164, 166};

    g.nodes[166].type = NodeType::Split;
    g.nodes[166].links = {168};

    g.nodes[167].type = NodeType::RuleRef;
    g.nodes[167].value = "selector";
    g.nodes[167].links = {169};

    g.nodes[168].type = NodeType::Split;
    g.nodes[168].links = {167, 169};

    g.nodes[169].type = NodeType::Split;
    g.nodes[169].links = {171};

    g.nodes[170].type = NodeType::RuleRef;
    g.nodes[170].value = "block";
    g.nodes[170].links = {172};

    g.nodes[171].type = NodeType::Split;
    g.nodes[171].links = {170, 172};

    g.nodes[172].type = NodeType::Split;
    g.nodes[172].links = {47};

    g.nodes[173].type = NodeType::MatchTok;
    g.nodes[173].value = "STRING";
    g.nodes[173].links = {49};

    g.nodes[174].type = NodeType::MatchTok;
    g.nodes[174].value = "NUMWORD";
    g.nodes[174].links = {49};

    g.nodes[175].type = NodeType::MatchTok;
    g.nodes[175].value = "KVWORD";
    g.nodes[175].links = {49};

    g.nodes[176].type = NodeType::MatchTok;
    g.nodes[176].value = "WORD";
    g.nodes[176].links = {49};

    g.nodes[177].type = NodeType::MatchTok;
    g.nodes[177].value = "NUMWORD";
    g.nodes[177].links = {51};

    g.nodes[178].type = NodeType::MatchTok;
    g.nodes[178].value = "KVWORD";
    g.nodes[178].links = {51};

    g.nodes[179].type = NodeType::MatchTok;
    g.nodes[179].value = "STRING";
    g.nodes[179].links = {51};

    g.nodes[180].type = NodeType::MatchStr;
    g.nodes[180].value = "[";
    g.nodes[180].links = {182};

    g.nodes[181].type = NodeType::RuleRef;
    g.nodes[181].value = "sel_word";
    g.nodes[181].links = {182};

    g.nodes[182].type = NodeType::Split;
    g.nodes[182].links = {181, 183};

    g.nodes[183].type = NodeType::Split;
    g.nodes[183].links = {184};

    g.nodes[184].type = NodeType::MatchStr;
    g.nodes[184].value = "]";
    g.nodes[184].links = {53};

    g.nodes[185].type = NodeType::MatchTok;
    g.nodes[185].value = "NUMWORD";
    g.nodes[185].links = {55};

    g.nodes[186].type = NodeType::MatchTok;
    g.nodes[186].value = "KVWORD";
    g.nodes[186].links = {55};

    g.nodes[187].type = NodeType::MatchTok;
    g.nodes[187].value = "WORD";
    g.nodes[187].links = {55};

    g.nodes[188].type = NodeType::MatchStr;
    g.nodes[188].value = "{";
    g.nodes[188].links = {190};

    g.nodes[189].type = NodeType::RuleRef;
    g.nodes[189].value = "body_item";
    g.nodes[189].links = {190};

    g.nodes[190].type = NodeType::Split;
    g.nodes[190].links = {189, 191};

    g.nodes[191].type = NodeType::Split;
    g.nodes[191].links = {192};

    g.nodes[192].type = NodeType::MatchStr;
    g.nodes[192].value = "}";
    g.nodes[192].links = {57};

    g.rules["assign_header"] = {26u, 27u};
    g.rules["block"] = {56u, 57u};
    g.rules["block_list"] = {8u, 9u};
    g.rules["body_item"] = {34u, 35u};
    g.rules["brace_body"] = {32u, 33u};
    g.rules["cont"] = {50u, 51u};
    g.rules["item"] = {2u, 3u};
    g.rules["key_tok"] = {38u, 39u};
    g.rules["nlq"] = {10u, 11u};
    g.rules["normal_val"] = {46u, 47u};
    g.rules["override_val"] = {42u, 43u};
    g.rules["plain_header"] = {28u, 29u};
    g.rules["prefer_block"] = {6u, 7u};
    g.rules["range_word"] = {14u, 15u};
    g.rules["rec_item"] = {18u, 19u};
    g.rules["record_body"] = {16u, 17u};
    g.rules["record_decl"] = {12u, 13u};
    g.rules["record_line"] = {20u, 21u};
    g.rules["rhs"] = {44u, 45u};
    g.rules["scene_file"] = {0u, 1u};
    g.rules["sel_word"] = {54u, 55u};
    g.rules["selector"] = {52u, 53u};
    g.rules["spectrum_decl"] = {24u, 25u};
    g.rules["stmt"] = {36u, 37u};
    g.rules["stop_word"] = {22u, 23u};
    g.rules["subtype"] = {30u, 31u};
    g.rules["top_block"] = {4u, 5u};
    g.rules["val_head"] = {48u, 49u};
    g.rules["value"] = {40u, 41u};

    g.skip_types = {"COMMENT", "WS"};
    g.start_rule = "scene_file";
    g.finalize();
    return g;
}

std::vector<gpda_lex::LexRule> ftsl_scene_lex_rules() {
    return {
        {"WS", "[ \\t\\r]+"},
        {"COMMENT", "#[^\\n]*"},
        {"NEWLINE", "\\n"},
        {"STRING", "\"[^\"]*\""},
        {"NUMWORD", "[+-]?([0-9]+\\.?[0-9]*|\\.[0-9]+)([eE][+-]?[0-9]+)?"},
        {"KVWORD", "[^ \\t\\r\\n{}\\[\\]#\"=]+=[^ \\t\\r\\n{}\\[\\]#\"]*"},
        {"WORD", "[^ \\t\\r\\n{}\\[\\]#\"]+"},
        {"_lit_1", "spectrum"},
        {"_lit_2", "prefer"},
        {"_lit_3", "range"},
        {"_lit_4", "else"},
        {"_lit_5", "="},
        {"_lit_6", "\\["},
        {"_lit_7", "\\]"},
        {"_lit_8", "\\{"},
        {"_lit_9", "\\}"},
    };
}

}  // namespace ftsl_gen
